{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.123.742.0 (23.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Factures 2021\",\"Sous famille\",\"Client\",\"Famille\",\"Groupe\",\"Nature\",\"Commerciaux\",\"Villes\",\"Produits\",\"Factures\",\"Budget\",\"Calendrier\",\"Indicateurs\",\"Source\",\"Exemple de fichier (2)\",\"Paramètre2\",\"Transformer l'exemple de fichier (2)\",\"Transformer le fichier (2)\",\"Dernier jour Ouvré Facturation\",\"CA - Marge\",\"KPI\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "fr-FR",
    "cultures": [
      {
        "name": "fr-FR",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "fr-FR",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "expressions": [
      {
        "name": "Factures 2021",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(File.Contents(Source & \"\\Factures\\2021\\Factures Tri 1 2021.csv\"),[Delimiter=\";\", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"En-têtes promus\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
          "    #\"Autres colonnes supprimées\" = Table.SelectColumns(#\"En-têtes promus\",{\"TotalVente\", \"ID\", \"PrixAchat\", \"PrixVente\", \"Quantite\", \"DateCommande\", \"DateFacture\", \"ClientId\", \"ProduitId\", \"NumeroFacture\"}),",
          "    #\"Type modifié\" = Table.TransformColumnTypes(#\"Autres colonnes supprimées\",{{\"TotalVente\", Int64.Type}, {\"ID\", Int64.Type}, {\"PrixAchat\", type number}, {\"PrixVente\", type number}, {\"Quantite\", Int64.Type}, {\"DateCommande\", type date}, {\"DateFacture\", type date}, {\"ClientId\", type text}, {\"ProduitId\", type text}, {\"NumeroFacture\", type text}}),",
          "    #\"Ajout nom du fichier\" = Table.AddColumn(#\"Type modifié\", \"Name\", each \"Factures Tri 1 2021.csv\"),",
          "    #\"Type modifié1\" = Table.TransformColumnTypes(#\"Ajout nom du fichier\",{{\"Name\", type text}})",
          "in",
          "    #\"Type modifié1\""
        ],
        "kind": "m",
        "lineageTag": "3b6a4b5f-0a1b-4b30-8ed6-bc8feb2c939d",
        "queryGroup": "Table de faits"
      },
      {
        "name": "Source",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"C:\\Users\\AurélieDuprez\\Documents\\Formation PBI\\Modèle formation\\Documents formation Power BI\\Fichier demo\" meta [IsParameterQuery=true, List={\"C:\\Users\\AurélieDuprez\\Documents\\Formation PBI\\Modèle formation\\Documents formation Power BI\\Fichier demo\"}, DefaultValue=\"C:\\Users\\AurélieDuprez\\Documents\\Formation PBI\\Modèle formation\\Documents formation Power BI\\Fichier demo\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "6cc9cd92-c2bc-4546-be62-731eef3b7eb8",
        "queryGroup": "Paramêtre"
      },
      {
        "name": "Exemple de fichier (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(Source &\"\\Factures\\2020\"),",
          "    #\"Fichiers masqués filtrés1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
          "    #\"Appeler une fonction personnalisée1\" = Table.AddColumn(#\"Fichiers masqués filtrés1\", \"Transformer le fichier (2)\", each #\"Transformer le fichier (2)\"([Content])),",
          "    Navigation1 = #\"Appeler une fonction personnalisée1\"{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "bb27c7ce-094d-4cb9-83ac-90b1437ce7c3",
        "queryGroup": "Facturation\\Transformer le fichier à partir de Base Facturation\\Requêtes d'assistance"
      },
      {
        "name": "Paramètre2",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": "#\"Exemple de fichier (2)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Exemple de fichier (2)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "f54b4374-926d-487f-892a-c601deebae30",
        "queryGroup": "Facturation\\Transformer le fichier à partir de Base Facturation\\Requêtes d'assistance"
      },
      {
        "name": "Transformer l'exemple de fichier (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(Paramètre2,[Delimiter=\";\", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "    #\"En-têtes promus\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"En-têtes promus\""
        ],
        "kind": "m",
        "lineageTag": "595f37b3-9c76-4254-918d-350ab88e43d1",
        "queryGroup": "Facturation\\Transformer le fichier à partir de Base Facturation"
      },
      {
        "name": "Transformer le fichier (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Paramètre2 as binary) => let",
          "        Source = Csv.Document(Paramètre2,[Delimiter=\";\", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
          "        #\"En-têtes promus\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "    in",
          "        #\"En-têtes promus\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "7c218e89-b04c-4d75-aad8-ef84df9d6ca9",
        "queryGroup": "Facturation\\Transformer le fichier à partir de Base Facturation\\Requêtes d'assistance"
      },
      {
        "name": "Famille",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(Source & \"\\Cas Pratique.xlsx\"), null, true),",
          "    Famille_Sheet = Source{[Item=\"Famille\",Kind=\"Sheet\"]}[Data],",
          "    #\"En-têtes promus\" = Table.PromoteHeaders(Famille_Sheet, [PromoteAllScalars=true]),",
          "    #\"Type modifié1\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"FamilleId\", type text}, {\"Famille\", type text}}),",
          "    #\"Filtrer <> Null\" = Table.SelectRows(#\"Type modifié1\", each ([Famille] <> null))",
          "in",
          "    #\"Filtrer <> Null\""
        ],
        "kind": "m",
        "lineageTag": "31427f5b-64d3-4656-99fc-2ae529a71bba",
        "queryGroup": "Tables de dimensions\\Tables dimension non chargée"
      },
      {
        "name": "Groupe",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(Source & \"\\Cas Pratique.xlsx\"), null, true),",
          "    Groupe_Sheet = Source{[Item=\"Groupe\",Kind=\"Sheet\"]}[Data],",
          "    #\"En-têtes promus\" = Table.PromoteHeaders(Groupe_Sheet, [PromoteAllScalars=true]),",
          "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"GroupeId\", Int64.Type}, {\"Groupe\", type text}})",
          "in",
          "    #\"Type modifié\""
        ],
        "kind": "m",
        "lineageTag": "a3412988-f88c-4993-afd8-3ec5305d335d",
        "queryGroup": "Tables de dimensions\\Tables dimension non chargée"
      },
      {
        "name": "Nature",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Excel.Workbook(File.Contents(Source & \"\\Cas Pratique.xlsx\"), null, true),",
          "    Nature_Sheet = Source{[Item=\"Nature\",Kind=\"Sheet\"]}[Data],",
          "    #\"En-têtes promus\" = Table.PromoteHeaders(Nature_Sheet, [PromoteAllScalars=true]),",
          "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"NatureId\", Int64.Type}, {\"Nature\", type text}})",
          "in",
          "    #\"Type modifié\""
        ],
        "kind": "m",
        "lineageTag": "0724e29f-47ba-4d5c-9103-16b5fa46c25d",
        "queryGroup": "Tables de dimensions\\Tables dimension non chargée"
      },
      {
        "name": "Dernier jour Ouvré Facturation",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": [
          "let",
          "    Source = List.Max(Factures[DateFacture])",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "93921840-993b-4b2f-87e2-2237fbf951b3",
        "queryGroup": "Paramêtre"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Facturation"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Facturation\\Transformer le fichier à partir de Base Facturation"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Facturation\\Transformer le fichier à partir de Base Facturation\\Requêtes d'assistance"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Paramêtre"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "Table de faits"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "Tables de dimensions"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Tables de dimensions\\Tables dimension non chargée"
      }
    ],
    "relationships": [
      {
        "name": "6be7be36-c40b-4336-843e-a22dd0c08626",
        "fromColumn": "Date Calendrier",
        "fromTable": "Calendrier",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a5c14128-44b1-489a-af52-976aaf8e8bef"
      },
      {
        "name": "594267df-fd47-42b3-b5d7-47c964afbd4e",
        "fromColumn": "Début de mois",
        "fromTable": "Calendrier",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_0bfa5a34-2fb2-43a4-9984-56c5a1d790dc"
      },
      {
        "name": "ea0e86a0-ef1a-46b2-98dd-d2e3a4d4aa3e",
        "fromColumn": "Fin du mois",
        "fromTable": "Calendrier",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_760eb492-0002-4761-bf71-1350a2012588"
      },
      {
        "name": "a90b946b-e676-4e95-8bed-bf7d621d4466",
        "fromColumn": "ClientId",
        "fromTable": "Factures",
        "toColumn": "ClientId",
        "toTable": "Client"
      },
      {
        "name": "d35f3031-c5f6-44d2-82f4-afff439efe42",
        "fromColumn": "ProduitId",
        "fromTable": "Factures",
        "toColumn": "ProduitId",
        "toTable": "Produits"
      },
      {
        "name": "ca73d64a-fc85-4464-9ce1-5e0d99e8ce96",
        "fromColumn": "Ville",
        "fromTable": "Client",
        "toColumn": "VillePays",
        "toTable": "Villes"
      },
      {
        "name": "9219829f-0e49-44bd-b228-9890510b0b37",
        "fromColumn": "IcId",
        "fromTable": "Client",
        "toColumn": "IcId",
        "toTable": "Commerciaux"
      },
      {
        "name": "95e0ad79-39f7-4364-b4b9-b0ceeef7fbdf",
        "fromColumn": "SousFamilleId",
        "fromTable": "Produits",
        "toColumn": "SousFamilleId",
        "toTable": "Sous famille"
      },
      {
        "name": "25c1207f-b9cd-4b5a-8b56-df2f6f6a1039",
        "fromColumn": "Commercial",
        "fromTable": "Budget",
        "toColumn": "IcId",
        "toTable": "Commerciaux"
      },
      {
        "name": "930ace1b-5957-40f2-a440-9bff4e185a04",
        "fromColumn": "SousFamille",
        "fromTable": "Budget",
        "toColumn": "SousFamille",
        "toTable": "Sous famille"
      },
      {
        "name": "3c48a8f9-ef04-4520-94b3-61105dbdd412",
        "fromColumn": "AnneeMois",
        "fromTable": "Budget",
        "toColumn": "Date Calendrier",
        "toTable": "Calendrier"
      },
      {
        "name": "eccf1290-e52c-4b9e-b02d-bdb85011cb66",
        "fromColumn": "DateFacture",
        "fromTable": "Factures",
        "toColumn": "Date Calendrier",
        "toTable": "Calendrier"
      },
      {
        "name": "ab94812c-89d4-4937-b86b-4af89f0cfcf8",
        "fromColumn": "DateCommande",
        "fromTable": "Factures",
        "isActive": false,
        "toColumn": "Date Calendrier",
        "toTable": "Calendrier"
      },
      {
        "name": "80f57377-2dd2-41f2-8299-fe080cfeb2ae",
        "fromColumn": "date -12 mois",
        "fromTable": "Calendrier",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4d7274eb-a370-43df-a354-1ee0cc1dda27"
      },
      {
        "name": "40cddd28-3f41-4b4c-931a-0573ebaf788d",
        "fromColumn": "datemin",
        "fromTable": "Tempo",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_9f42d532-2871-464a-9fd2-01ce197590de"
      },
      {
        "name": "64401fa8-8efd-4d32-a841-6f22fa1be5dc",
        "fromColumn": "datemax",
        "fromTable": "Tempo",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_970ea407-f151-4376-b6fb-9d371f24cc83"
      }
    ],
    "roles": [
      {
        "name": "Hommes",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0ac38fca733c4766a15743302003077e"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Commerciaux",
            "filterExpression": "[Genre] = \"Homme\""
          }
        ]
      },
      {
        "name": "Femmes",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "13185e3e803a41abb0aeeb28c80ce6b8"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Commerciaux",
            "filterExpression": "[Genre] = \"Femme\""
          }
        ]
      }
    ],
    "sourceQueryCulture": "fr-FR",
    "tables": [
      {
        "name": "DateTableTemplate_a97739a8-6c32-415c-872f-cc4e8a98baf8",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "453a4827-37f6-4436-9c20-fdb8826ba952",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Année",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e8f76d73-c0cb-4d31-8e77-2b24ee0f2823",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoMois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5dfe2ca4-22ec-438e-858d-90d3bfb3a04e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "441aac56-a148-4663-8799-80262d3ffc96",
            "sortByColumn": "NoMois",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NoMois] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c21c7841-ecd9-4f45-bd3a-5e4d48e68318",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [NoTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ddd29b6e-d72a-4209-91b5-0b5ddfcf9754",
            "sortByColumn": "NoTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Jour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "291336b9-17b5-41a6-af0c-e2573313c317",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Année",
                "column": "Année",
                "lineageTag": "0e690a43-0ed3-4fc4-84db-fa415f62b595",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "eaf8dcb6-8e22-4814-995f-16bc3868c04b",
                "ordinal": 1
              },
              {
                "name": "Mois",
                "column": "Mois",
                "lineageTag": "6e4651ba-209b-4847-82bb-9b33675e4a41",
                "ordinal": 2
              },
              {
                "name": "Jour",
                "column": "Jour",
                "lineageTag": "ae260d76-109f-493f-b5a7-5a69d23a3496",
                "ordinal": 3
              }
            ],
            "lineageTag": "a9973e1d-938d-412c-9e58-fb31e9bdf24f"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "79d26767-2d65-4fe3-9ff2-4ef45f084459",
        "partitions": [
          {
            "name": "DateTableTemplate_a97739a8-6c32-415c-872f-cc4e8a98baf8-5aa4b749-1861-4ff0-9df6-4d5abb6da66b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Budget",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0227a04b-dba8-4924-8d17-95fba7b05673"
          },
          {
            "name": "LinkedQueryName",
            "value": "Budget"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":8,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Budget/Type modifié.{Nom,0}\",\"Section1/Budget/Type modifié.{SousFamille,1}\",\"Section1/Budget/Type modifié.{Mois,2}\",\"Section1/Budget/Type modifié.{Montant,3}\",\"Section1/Budget/Type modifié.{Annee,4}\",\"Section1/Budget/Type modifié.{Commercial,5}\",\"Section1/Budget/Type modifié.{CodeBudget,6}\",\"Section1/Budget/Type modifié.{AnneeMois,7}\"],\"ColumnCount\":8,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Budget/Type modifié.{Nom,0}\",\"Section1/Budget/Type modifié.{SousFamille,1}\",\"Section1/Budget/Type modifié.{Mois,2}\",\"Section1/Budget/Type modifié.{Montant,3}\",\"Section1/Budget/Type modifié.{Annee,4}\",\"Section1/Budget/Type modifié.{Commercial,5}\",\"Section1/Budget/Type modifié.{CodeBudget,6}\",\"Section1/Budget/Type modifié.{AnneeMois,7}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "SousFamille",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f3963323-31dc-4f35-b82b-f488a386c8e3",
            "sourceColumn": "SousFamille",
            "summarizeBy": "none"
          },
          {
            "name": "Montant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "38038827-0077-4d8f-bcb3-3bcc473e186c",
            "sourceColumn": "Montant",
            "summarizeBy": "sum"
          },
          {
            "name": "Commercial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a246097d-76b7-4856-bab4-a6cd05772983",
            "sourceColumn": "Commercial",
            "summarizeBy": "none"
          },
          {
            "name": "AnneeMois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isHidden": true,
            "lineageTag": "64f7ac73-3650-4bd2-9deb-41b9b144796a",
            "sourceColumn": "AnneeMois",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "6800d88d-8015-48e1-a647-b203f2472903",
        "partitions": [
          {
            "name": "Budget-d7b409ce-0459-432a-9015-6db28670f7fc",
            "mode": "import",
            "queryGroup": "Table de faits",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(Source & \"\\Cas Pratique.xlsx\"), null, true),",
                "    Budget_Sheet = Source{[Item=\"Budget\",Kind=\"Sheet\"]}[Data],",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Budget_Sheet, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"Nom\", type text}, {\"SousFamille\", type text}, {\"Mois\", Int64.Type}, {\"Montant\", Int64.Type}, {\"Annee\", Int64.Type}, {\"Commercial\", type text}, {\"CodeBudget\", type date}, {\"AnneeMois\", type date}}),",
                "    #\"Col. sup. CodeBud Mois Année Nom Col.9\" = Table.RemoveColumns(#\"Type modifié\",{\"Column9\", \"CodeBudget\", \"Mois\", \"Annee\", \"Nom\"})",
                "in",
                "    #\"Col. sup. CodeBud Mois Année Nom Col.9\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Client",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a7a4014b-e01e-4e17-a887-591a594645d6"
          },
          {
            "name": "LinkedQueryName",
            "value": "Client"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":11,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Client/Type modifié.{ClientId,0}\",\"Section1/Client/Type modifié.{CodePostal,1}\",\"Section1/Client/Type modifié.{Ville,2}\",\"Section1/Client/Type modifié.{Enseigne,3}\",\"Section1/Client/Type modifié.{NatureId,4}\",\"Section1/Client/Type modifié.{GroupeId,5}\",\"Section1/Client/Type modifié.{IcId,6}\",\"Section1/Client/Type modifié.{NbJourEcheance,7}\",\"Section1/Client/Type modifié.{Pays,8}\",\"Section1/Client/Type modifié.{VillePays,9}\",\"Section1/Client/Type modifié.{PaysVille,10}\"],\"ColumnCount\":11,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Client/Type modifié.{ClientId,0}\",\"Section1/Client/Type modifié.{CodePostal,1}\",\"Section1/Client/Type modifié.{Ville,2}\",\"Section1/Client/Type modifié.{Enseigne,3}\",\"Section1/Client/Type modifié.{NatureId,4}\",\"Section1/Client/Type modifié.{GroupeId,5}\",\"Section1/Client/Type modifié.{IcId,6}\",\"Section1/Client/Type modifié.{NbJourEcheance,7}\",\"Section1/Client/Type modifié.{Pays,8}\",\"Section1/Client/Type modifié.{VillePays,9}\",\"Section1/Client/Type modifié.{PaysVille,10}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ClientId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6df01924-f767-4cb2-9a9c-fb6f5875e878",
            "sourceColumn": "ClientId",
            "summarizeBy": "none"
          },
          {
            "name": "CodePostal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PostalCode",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "23c3174e-8cad-4459-b54c-be038bbea005",
            "sourceColumn": "CodePostal",
            "summarizeBy": "none"
          },
          {
            "name": "Ville",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d783fd8f-05e6-4234-8b8a-565fa2d8f95f",
            "sourceColumn": "Ville",
            "summarizeBy": "none"
          },
          {
            "name": "Enseigne",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ddafbb8a-c0e3-4e6b-ae9a-8dc68e326fec",
            "sourceColumn": "Enseigne",
            "summarizeBy": "none"
          },
          {
            "name": "IcId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84d9d8df-4b01-42bc-8229-3b1466352acf",
            "sourceColumn": "IcId",
            "summarizeBy": "none"
          },
          {
            "name": "NbJourEcheance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "18ec6895-c877-4219-ab83-35eda849463e",
            "sourceColumn": "NbJourEcheance",
            "summarizeBy": "none"
          },
          {
            "name": "Pays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d9ef2d1-5a9d-4d5d-8c1c-6966a19c3461",
            "sourceColumn": "Pays",
            "summarizeBy": "none"
          },
          {
            "name": "VillePays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f3a22c1-e895-4c47-85be-66806d21fc35",
            "sourceColumn": "VillePays",
            "summarizeBy": "none"
          },
          {
            "name": "PaysVille",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e603de99-3c0f-4585-a7bc-22c9157a1232",
            "sourceColumn": "PaysVille",
            "summarizeBy": "none"
          },
          {
            "name": "Nature",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3ddfbc7-f5db-4270-892f-4dace4653785",
            "sourceColumn": "Nature",
            "summarizeBy": "none"
          },
          {
            "name": "Groupe",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd1d47ec-0588-4b49-980e-e23e9f6e98d6",
            "sourceColumn": "Groupe",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "67a096b8-b583-42a3-b7f1-c8da4684097f",
        "measures": [
          {
            "name": "Nb clients distincts",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DISTINCTCOUNT(Client[ClientId])",
            "lineageTag": "4f44b397-cadd-447d-b8ce-bb89ea22740c"
          }
        ],
        "partitions": [
          {
            "name": "Client-d67b20c9-2b76-4a0e-bc1d-ff77c01479e4",
            "mode": "import",
            "queryGroup": "Tables de dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(Source & \"\\Cas Pratique.xlsx\"), null, true),",
                "    Client_Sheet = Source{[Item=\"Client\",Kind=\"Sheet\"]}[Data],",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Client_Sheet, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"ClientId\", type text}, {\"CodePostal\", Int64.Type}, {\"Ville\", type text}, {\"Enseigne\", type text}, {\"NatureId\", Int64.Type}, {\"GroupeId\", Int64.Type}, {\"IcId\", type text}, {\"NbJourEcheance\", Int64.Type}, {\"Pays\", type text}, {\"VillePays\", type text}, {\"PaysVille\", type text}}),",
                "    #\"Fusion sur la table Nature\" = Table.NestedJoin(#\"Type modifié\", {\"NatureId\"}, Nature, {\"NatureId\"}, \"Nature\", JoinKind.LeftOuter),",
                "    #\"Nature développé\" = Table.ExpandTableColumn(#\"Fusion sur la table Nature\", \"Nature\", {\"Nature\"}, {\"Nature\"}),",
                "    #\"Fusion sur la table Groupe\" = Table.NestedJoin(#\"Nature développé\", {\"GroupeId\"}, Groupe, {\"GroupeId\"}, \"Groupe\", JoinKind.LeftOuter),",
                "    #\"Groupe développé\" = Table.ExpandTableColumn(#\"Fusion sur la table Groupe\", \"Groupe\", {\"Groupe\"}, {\"Groupe\"}),",
                "    #\"Col. sup. NatureId & GroupeId\" = Table.RemoveColumns(#\"Groupe développé\",{\"NatureId\", \"GroupeId\"})",
                "in",
                "    #\"Col. sup. NatureId & GroupeId\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Commerciaux",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "006259d1-fec4-4837-9291-c472e553eabb"
          },
          {
            "name": "LinkedQueryName",
            "value": "Commerciaux"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":3,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Commerciaux/Type modifié.{IcId,0}\",\"Section1/Commerciaux/Type modifié.{NomCommercial,1}\",\"Section1/Commerciaux/Type modifié.{Photo,2}\"],\"ColumnCount\":3,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Commerciaux/Type modifié.{IcId,0}\",\"Section1/Commerciaux/Type modifié.{NomCommercial,1}\",\"Section1/Commerciaux/Type modifié.{Photo,2}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "IcId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3178d17c-f569-42be-995b-ffa5100f8779",
            "sourceColumn": "IcId",
            "summarizeBy": "none"
          },
          {
            "name": "NomCommercial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Commerciaux\",\"TableItemName\":\"Genre\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "lineageTag": "92d9dbea-09fb-4b93-8dc2-ba318dd509e7",
            "sourceColumn": "NomCommercial",
            "summarizeBy": "none"
          },
          {
            "name": "Bon moins bon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "if([Tx de marge]>0.65,\"bon\",\"moins bon\")",
            "isDataTypeInferred": true,
            "lineageTag": "0621a7c0-698e-4a33-97f0-c8129178ce98",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Genre",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"c\",\"Entity\":\"Commerciaux\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"c\"}},\"Property\":\"NomCommercial\"}}],\"GroupItems\":[{\"DisplayName\":\"(Vide)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"Femme\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"c\"}},\"Property\":\"NomCommercial\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Aline Martin'\"}}],[{\"Literal\":{\"Value\":\"'Ludivine COLLIN'\"}}],[{\"Literal\":{\"Value\":\"'Ludivine Martin'\"}}],[{\"Literal\":{\"Value\":\"'Sophie Morand'\"}}]]}}},{\"DisplayName\":\"Homme\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"c\"}},\"Property\":\"NomCommercial\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Luc Albert'\"}}],[{\"Literal\":{\"Value\":\"'Paul Derwin'\"}}],[{\"Literal\":{\"Value\":\"'Raoul Marciac'\"}}]]}}}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(",
              "\tTRUE,",
              "\tISBLANK('Commerciaux'[NomCommercial]),",
              "\t\"(Vide)\",",
              "\t'Commerciaux'[NomCommercial] IN {\"Aline Martin\",",
              "\t\t\"Ludivine COLLIN\",",
              "\t\t\"Ludivine Martin\",",
              "\t\t\"Sophie Morand\"},",
              "\t\"Femme\",",
              "\t'Commerciaux'[NomCommercial] IN {\"Luc Albert\",",
              "\t\t\"Paul Derwin\",",
              "\t\t\"Raoul Marciac\"},",
              "\t\"Homme\",",
              "\t'Commerciaux'[NomCommercial]",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Commerciaux"
                          }
                        },
                        "Property": "NomCommercial"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "992f5abe-0e83-4d3c-9fbc-d77aaf996bdc",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "94ed1ef2-65d0-4cf8-8d3d-cc331a8b9f53",
        "partitions": [
          {
            "name": "Commerciaux-e3ab2cc9-c86c-452a-bb1b-4d2d0c638514",
            "mode": "import",
            "queryGroup": "Tables de dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(Source & \"\\Cas Pratique.xlsx\"), null, true),",
                "    Commerciaux_Sheet = Source{[Item=\"Commerciaux\",Kind=\"Sheet\"]}[Data],",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Commerciaux_Sheet, [PromoteAllScalars=true]),",
                "    #\"Garde IcId & NomCom.\" = Table.SelectColumns(#\"En-têtes promus\",{\"IcId\", \"NomCommercial\"}),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"Garde IcId & NomCom.\",{{\"IcId\", type text}, {\"NomCommercial\", type text}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Villes",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b6b7a5c7-d559-4e4e-8f02-e6a80ea8341e"
          },
          {
            "name": "LinkedQueryName",
            "value": "Villes"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":3,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Villes/Type modifié.{VillePays,0}\",\"Section1/Villes/Type modifié.{Latitude,1}\",\"Section1/Villes/Type modifié.{Longitude,2}\"],\"ColumnCount\":3,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Villes/Type modifié.{VillePays,0}\",\"Section1/Villes/Type modifié.{Latitude,1}\",\"Section1/Villes/Type modifié.{Longitude,2}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "VillePays",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "14ee1eea-f9dc-4fb1-9204-8924ea5954b6",
            "sourceColumn": "VillePays",
            "summarizeBy": "none"
          },
          {
            "name": "Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "Latitude",
            "dataType": "double",
            "lineageTag": "c973166c-206a-4264-8d1d-6f4e70c7f00c",
            "sourceColumn": "Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataCategory": "Longitude",
            "dataType": "double",
            "lineageTag": "14941b1b-fa42-4de3-9bfc-e36c6a163fbc",
            "sourceColumn": "Longitude",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "56b89808-3da4-4e1d-aa8f-bd49553159b4",
        "partitions": [
          {
            "name": "Villes-c7458329-4ec2-4577-8c6d-ffd8ec1844c3",
            "mode": "import",
            "queryGroup": "Tables de dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(Source & \"\\Cas Pratique.xlsx\"), null, true),",
                "    Villes_Sheet = Source{[Item=\"Villes\",Kind=\"Sheet\"]}[Data],",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Villes_Sheet, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"VillePays\", type text}, {\"Latitude\", type number}, {\"Longitude\", type number}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Produits",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4f45c075-931a-4dae-9099-ec4c7a5f1c4d"
          },
          {
            "name": "LinkedQueryName",
            "value": "Produits"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":15,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Produits/Type modifié.{ProduitId,0}\",\"Section1/Produits/Type modifié.{NomProduit,1}\",\"Section1/Produits/Type modifié.{Designation,2}\",\"Section1/Produits/Type modifié.{SousFamilleId,3}\",\"Section1/Produits/Type modifié.{Conditionnement,4}\",\"Section1/Produits/Type modifié.{Prix,5}\",\"Section1/Produits/Type modifié.{Origine,6}\",\"Section1/Produits/Type modifié.{Type,7}\",\"Section1/Produits/Type modifié.{Photos,8}\",\"Section1/Produits/Type modifié.{Numero,9}\",\"Section1/Produits/Type modifié.{TotalCAProduit,10}\",\"Section1/Produits/Type modifié.{CaProduitGlobal,11}\",\"Section1/Produits/Type modifié.{CumulCAProduit,12}\",\"Section1/Produits/Type modifié.{PourcentProduit,13}\",\"Section1/Produits/Type modifié.{ABCProduit,14}\"],\"ColumnCount\":15,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Produits/Type modifié.{ProduitId,0}\",\"Section1/Produits/Type modifié.{NomProduit,1}\",\"Section1/Produits/Type modifié.{Designation,2}\",\"Section1/Produits/Type modifié.{SousFamilleId,3}\",\"Section1/Produits/Type modifié.{Conditionnement,4}\",\"Section1/Produits/Type modifié.{Prix,5}\",\"Section1/Produits/Type modifié.{Origine,6}\",\"Section1/Produits/Type modifié.{Type,7}\",\"Section1/Produits/Type modifié.{Photos,8}\",\"Section1/Produits/Type modifié.{Numero,9}\",\"Section1/Produits/Type modifié.{TotalCAProduit,10}\",\"Section1/Produits/Type modifié.{CaProduitGlobal,11}\",\"Section1/Produits/Type modifié.{CumulCAProduit,12}\",\"Section1/Produits/Type modifié.{PourcentProduit,13}\",\"Section1/Produits/Type modifié.{ABCProduit,14}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProduitId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4eac83e7-bf93-4644-a6b5-e3e32545a422",
            "sourceColumn": "ProduitId",
            "summarizeBy": "none"
          },
          {
            "name": "NomProduit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Produits\",\"TableItemName\":\"NomProduit (groupes)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"},{\"LinkTarget\":{\"TableName\":\"Produits\",\"TableItemName\":\"NomProduit (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "lineageTag": "17fcebeb-8a75-409b-8418-41659277bcd2",
            "sourceColumn": "NomProduit",
            "summarizeBy": "none"
          },
          {
            "name": "Designation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f85746d5-6355-4905-9aaa-ffff556581cf",
            "sourceColumn": "Designation",
            "summarizeBy": "none"
          },
          {
            "name": "SousFamilleId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1b7735bc-ea99-4ddc-8662-69309760de40",
            "sourceColumn": "SousFamilleId",
            "summarizeBy": "none"
          },
          {
            "name": "Conditionnement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "100386ba-213c-48ae-b3e3-a0b3975c91e7",
            "sourceColumn": "Conditionnement",
            "summarizeBy": "none"
          },
          {
            "name": "Prix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "30a40341-09da-4129-b843-777b2d71ac60",
            "sourceColumn": "Prix",
            "summarizeBy": "none"
          },
          {
            "name": "Origine",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Produits\",\"TableItemName\":\"Continent Origine\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "lineageTag": "963cdb45-df77-499f-8a78-0d90821925e0",
            "sourceColumn": "Origine",
            "summarizeBy": "none"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cce993b2-8d2a-4c93-9db3-5553083db412",
            "sourceColumn": "Type",
            "summarizeBy": "none"
          },
          {
            "name": "Photos",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae448025-e1b8-407a-90f8-6ccde0671628",
            "sourceColumn": "Photos",
            "summarizeBy": "none"
          },
          {
            "name": "Numero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8d598526-5200-4a7d-aa3b-a13f195b56ed",
            "sourceColumn": "Numero",
            "summarizeBy": "none"
          },
          {
            "name": "Total marge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "CALCULATE(sum('Factures'[Marge]))",
            "isDataTypeInferred": true,
            "lineageTag": "db80f568-81d2-4f8e-9f34-bb9daf5dfd85",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "NomProduit (groupes)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"p\",\"Entity\":\"Produits\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"NomProduit\"}}],\"GroupItems\":[{\"DisplayName\":\"(Vide)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"A\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"NomProduit\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Abricot'\"}}],[{\"Literal\":{\"Value\":\"'Agrumes'\"}}],[{\"Literal\":{\"Value\":\"'Ail'\"}}],[{\"Literal\":{\"Value\":\"'Ananas'\"}}],[{\"Literal\":{\"Value\":\"'Artichaut'\"}}],[{\"Literal\":{\"Value\":\"'Aubergine'\"}}],[{\"Literal\":{\"Value\":\"'Avocat'\"}}]]}}},{\"DisplayName\":\"B-E\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"NomProduit\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Banane'\"}}],[{\"Literal\":{\"Value\":\"'Bananes'\"}}],[{\"Literal\":{\"Value\":\"'Brocoli'\"}}],[{\"Literal\":{\"Value\":\"'Carotte'\"}}],[{\"Literal\":{\"Value\":\"'Chou'\"}}],[{\"Literal\":{\"Value\":\"'Concombre'\"}}],[{\"Literal\":{\"Value\":\"'Courgette'\"}}],[{\"Literal\":{\"Value\":\"'Echalotte'\"}}],[{\"Literal\":{\"Value\":\"'Epinard'\"}}]]}}},{\"DisplayName\":\"F-M\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"NomProduit\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Fenouil'\"}}],[{\"Literal\":{\"Value\":\"'Fèves'\"}}],[{\"Literal\":{\"Value\":\"'Fraise'\"}}],[{\"Literal\":{\"Value\":\"'Framboise'\"}}],[{\"Literal\":{\"Value\":\"'Fruits exotiques'\"}}],[{\"Literal\":{\"Value\":\"'Haricot'\"}}],[{\"Literal\":{\"Value\":\"'Haricot sec'\"}}],[{\"Literal\":{\"Value\":\"'Lentille'\"}}],[{\"Literal\":{\"Value\":\"'Melon'\"}}]]}}},{\"DisplayName\":\"Autre\"}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(",
              "  TRUE,",
              "  ISBLANK('Produits'[NomProduit]),",
              "  \"(Vide)\",",
              "  'Produits'[NomProduit] IN {\"Abricot\",",
              "    \"Agrumes\",",
              "    \"Ail\",",
              "    \"Ananas\",",
              "    \"Artichaut\",",
              "    \"Aubergine\",",
              "    \"Avocat\"},",
              "  \"A\",",
              "  'Produits'[NomProduit] IN {\"Banane\",",
              "    \"Bananes\",",
              "    \"Brocoli\",",
              "    \"Carotte\",",
              "    \"Chou\",",
              "    \"Concombre\",",
              "    \"Courgette\",",
              "    \"Echalotte\",",
              "    \"Epinard\"},",
              "  \"B-E\",",
              "  'Produits'[NomProduit] IN {\"Fenouil\",",
              "    \"Fèves\",",
              "    \"Fraise\",",
              "    \"Framboise\",",
              "    \"Fruits exotiques\",",
              "    \"Haricot\",",
              "    \"Haricot sec\",",
              "    \"Lentille\",",
              "    \"Melon\"},",
              "  \"F-M\",",
              "  \"Autre\"",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Produits"
                          }
                        },
                        "Property": "NomProduit"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "c8b87a1e-7e32-49fa-8bf6-5fbb84e4fd7f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NomProduit (clusters)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"p\",\"Entity\":\"Produits\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"NomProduit\"}}],\"PartitionTable\":{\"Definition\":{\"TableDefinition\":{\"Version\":2,\"From\":[{\"Name\":\"i\",\"Entity\":\"Indicateurs\"},{\"Name\":\"p\",\"Entity\":\"Produits\"}],\"Where\":[],\"OrderBy\":[],\"Select\":[{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"output0\"}},\"Property\":\"Produits.NomProduit\"},\"Name\":\"Produits.NomProduit\"},{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"output0\"}},\"Property\":\"clusterId\"},\"Name\":\"clusterId\"}],\"GroupBy\":[],\"Transform\":[{\"Name\":\"KMeansClustering\",\"Algorithm\":\"KMeansClustering\",\"Input\":{\"Parameters\":[{\"Literal\":{\"Value\":\"5L\"},\"Name\":\"NumberOfClusters\"}],\"Table\":{\"Name\":\"input0\",\"Columns\":[{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"i\"}},\"Property\":\"CA Total\"},\"Name\":\"Indicateurs.CA Total\"}},{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"i\"}},\"Property\":\"Tx de marge\"},\"Name\":\"Indicateurs.Tx de marge\"}},{\"Role\":\"Item\",\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"NomProduit\"},\"Name\":\"Produits.NomProduit\"}}]}},\"Output\":{\"Table\":{\"Name\":\"output0\",\"Columns\":[{\"Expression\":{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"input0\"}},\"Property\":\"Produits.NomProduit\"},\"Name\":\"Produits.NomProduit\"}},{\"Role\":\"Series\",\"Expression\":{\"TransformOutputRoleRef\":{\"Role\":\"ClusterId\"},\"Name\":\"clusterId\"}}]}}}]},\"ItemIdColumns\":[\"Produits.NomProduit\"],\"PartitionIdColumn\":\"clusterId\",\"Partitions\":[{\"PartitionIds\":[{\"Literal\":{\"Value\":\"null\"}}]}],\"DefaultPartitionPrefix\":\"Cluster\"},\"Result\":{\"TableName\":\"ClusterMappingTable\",\"PartitionIdColumn\":\"ClusterId\",\"ItemIdMappings\":[[{\"PartitionTableColumn\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Entity\":\"ClusterMappingTable\"}},\"Property\":\"NomProduit\"}},\"SourceTableColumn\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Entity\":\"Produits\"}},\"Property\":\"NomProduit\"}}}]]}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Clusters pour NomProduit",
            "expression": [
              "VAR __ClusterValue = ",
              "  LOOKUPVALUE(",
              "    'ClusterMappingTable'[ClusterId],",
              "    'ClusterMappingTable'[NomProduit],",
              "    'Produits'[NomProduit]",
              "  )",
              "",
              "RETURN",
              "  SWITCH(",
              "    __ClusterValue,",
              "    BLANK(),",
              "    BLANK(),",
              "    CONCATENATE(\"Cluster\", __ClusterValue)",
              "  )"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Produits"
                          }
                        },
                        "Property": "NomProduit"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "094a01d6-ec33-425a-8412-a04300fe764e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Nb produits par S-F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "CALCULATE(DISTINCTCOUNT(Produits[ProduitId]), FILTER(Produits, Produits[SousFamilleId] = EARLIER(Produits[SousFamilleId])))",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "e8b725a3-b7ac-4f86-9c49-8e22f51f7b99",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Continent Origine",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"p\",\"Entity\":\"Produits\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"Origine\"}}],\"GroupItems\":[{\"DisplayName\":\"(Vide)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"Europe\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"p\"}},\"Property\":\"Origine\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'Belgique'\"}}],[{\"Literal\":{\"Value\":\"'Espagne'\"}}],[{\"Literal\":{\"Value\":\"'France'\"}}],[{\"Literal\":{\"Value\":\"'Grêce'\"}}],[{\"Literal\":{\"Value\":\"'Italie'\"}}],[{\"Literal\":{\"Value\":\"'Portugal'\"}}]]}}}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(",
              "\tTRUE,",
              "\tISBLANK('Produits'[Origine]),",
              "\t\"(Vide)\",",
              "\t'Produits'[Origine] IN {\"Belgique\",",
              "\t\t\"Espagne\",",
              "\t\t\"France\",",
              "\t\t\"Grêce\",",
              "\t\t\"Italie\",",
              "\t\t\"Portugal\"},",
              "\t\"Europe\",",
              "\t'Produits'[Origine]",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Produits"
                          }
                        },
                        "Property": "Origine"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "8a849916-0a09-4a36-8f25-fd81fc83ca1f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie Produit",
            "levels": [
              {
                "name": "NomProduit",
                "column": "NomProduit",
                "lineageTag": "a8daff06-eda0-43f4-8160-477f1e6b8383",
                "ordinal": 0
              },
              {
                "name": "Conditionnement",
                "column": "Conditionnement",
                "lineageTag": "c5c0d56b-1572-4cbf-8224-55d3f8df2752",
                "ordinal": 1
              }
            ],
            "lineageTag": "75fa848b-ad55-4c1d-aacb-702e5c3cf791"
          },
          {
            "name": "Type Hiérarchie",
            "levels": [
              {
                "name": "Type",
                "column": "Type",
                "lineageTag": "f232bbc6-c893-4209-a027-e31493e01f8f",
                "ordinal": 0
              },
              {
                "name": "NomProduit",
                "column": "NomProduit",
                "lineageTag": "870af128-e909-4762-8cde-8750456f4aa6",
                "ordinal": 1
              }
            ],
            "lineageTag": "2c8760e9-fe56-48cb-9617-6bc5de4a0ecf"
          }
        ],
        "lineageTag": "189548ea-78dc-4642-9b93-894201acc491",
        "partitions": [
          {
            "name": "Produits-8a0fff30-518f-47a4-b397-aea94cf0c966",
            "mode": "import",
            "queryGroup": "Tables de dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(Source & \"\\Cas Pratique.xlsx\"), null, true),",
                "    Produits_Sheet = Source{[Item=\"Produits\",Kind=\"Sheet\"]}[Data],",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Produits_Sheet, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"ProduitId\", type text}, {\"NomProduit\", type text}, {\"Designation\", type text}, {\"SousFamilleId\", type text}, {\"Conditionnement\", Int64.Type}, {\"Prix\", Int64.Type}, {\"Origine\", type text}, {\"Type\", type text}, {\"Photos\", type text}, {\"Numero\", Int64.Type}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Factures",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "71466351-a4e1-4bd9-b0a0-1632be239081"
          },
          {
            "name": "LinkedQueryName",
            "value": "Base Facturation"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":14,\"keyColumnNames\":[],\"queryRelationships\":[{\"keyColumnCount\":1,\"keyColumn\":2,\"otherKeyColumnIdentity\":\"Section1/Client/Type modifié.{ClientId,0}\",\"KeyColumnCount\":1}],\"columnIdentities\":[\"Section1/Base Facturation/Requête ajoutée.{NumeroFacture,0}\",\"Section1/Base Facturation/Requête ajoutée.{ProduitId,1}\",\"Section1/Base Facturation/Requête ajoutée.{ClientId,2}\",\"Section1/Base Facturation/Requête ajoutée.{DateFacture,3}\",\"Section1/Base Facturation/Requête ajoutée.{PrixVenteSaison,4}\",\"Section1/Base Facturation/Requête ajoutée.{Quantite,5}\",\"Section1/Base Facturation/Requête ajoutée.{PrixVente,6}\",\"Section1/Base Facturation/Requête ajoutée.{CoeffSaison,7}\",\"Section1/Base Facturation/Requête ajoutée.{PrixAchat,8}\",\"Section1/Base Facturation/Requête ajoutée.{ID,9}\",\"Section1/Base Facturation/Requête ajoutée.{TotalCaLigne,10}\",\"Section1/Base Facturation/Requête ajoutée.{Source.Name,11}\",\"Section1/Client/Type modifié.{Ville,2}\",\"Section1/Base Facturation/Soustraction insérée.{Soustraction,13}\"],\"ColumnCount\":14,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Base Facturation/Requête ajoutée.{NumeroFacture,0}\",\"Section1/Base Facturation/Requête ajoutée.{ProduitId,1}\",\"Section1/Base Facturation/Requête ajoutée.{ClientId,2}\",\"Section1/Base Facturation/Requête ajoutée.{DateFacture,3}\",\"Section1/Base Facturation/Requête ajoutée.{PrixVenteSaison,4}\",\"Section1/Base Facturation/Requête ajoutée.{Quantite,5}\",\"Section1/Base Facturation/Requête ajoutée.{PrixVente,6}\",\"Section1/Base Facturation/Requête ajoutée.{CoeffSaison,7}\",\"Section1/Base Facturation/Requête ajoutée.{PrixAchat,8}\",\"Section1/Base Facturation/Requête ajoutée.{ID,9}\",\"Section1/Base Facturation/Requête ajoutée.{TotalCaLigne,10}\",\"Section1/Base Facturation/Requête ajoutée.{Source.Name,11}\",\"Section1/Client/Type modifié.{Ville,2}\",\"Section1/Base Facturation/Soustraction insérée.{Soustraction,13}\"],\"RelationshipInfo\":[{\"keyColumnCount\":1,\"keyColumn\":2,\"otherKeyColumnIdentity\":\"Section1/Client/Type modifié.{ClientId,0}\",\"KeyColumnCount\":1}]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "NumeroFacture",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Factures\",\"TableItemName\":\"NumeroFacture (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2ba66fa8-9a06-4764-82e6-50dd7aed268d",
            "sourceColumn": "NumeroFacture",
            "summarizeBy": "none"
          },
          {
            "name": "ProduitId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "53a81d27-1e18-488c-b084-52129f53d6f3",
            "sourceColumn": "ProduitId",
            "summarizeBy": "none"
          },
          {
            "name": "ClientId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "68a32cae-cbb1-4f8a-8eca-54aa1e25fc9e",
            "sourceColumn": "ClientId",
            "summarizeBy": "none"
          },
          {
            "name": "DateFacture",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "isHidden": true,
            "lineageTag": "7594a6a7-9b12-4154-a5de-930e9c4e12f8",
            "sourceColumn": "DateFacture",
            "summarizeBy": "none"
          },
          {
            "name": "Quantite",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "88bd6fb2-cc62-4571-81cf-3b5d34b01323",
            "sourceColumn": "Quantite",
            "summarizeBy": "sum"
          },
          {
            "name": "PrixVente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Factures\",\"TableItemName\":\"Gpe Prix de vente\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "72765bb5-68a1-4d6b-8154-52cdc191a0b0",
            "sourceColumn": "PrixVente",
            "summarizeBy": "none"
          },
          {
            "name": "PrixAchat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "7fa56f14-c618-4618-9975-729cc48c6e8e",
            "sourceColumn": "PrixAchat",
            "summarizeBy": "none"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7ab51f38-2ee5-4bea-890a-7905354b75e2",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Ville",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "554eda24-0134-44cb-a537-a3a35ae3d86b",
            "sourceColumn": "Ville",
            "summarizeBy": "none"
          },
          {
            "name": "Marge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "expression": "'Factures'[Marge Unitaire]*'Factures'[Quantite]",
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b7f5e80e-d8d2-4768-933b-97e5c406efd7",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "% de marge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "displayFolder": "Autres trucs",
            "expression": "DIVIDE('Factures'[Marge],'Factures'[CA])",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "abcc7f76-ddc7-4c65-849f-35e35829856d",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Bon moins bon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "if('Factures'[% de marge]>0.5,\"Bon\",\"Moins Bon\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3cd21d3f-7829-43d1-84ec-af34addf06bc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Origine produit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "RELATED(Produits[Origine])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8ea7b83c-b583-4b84-8839-1f88b76af73d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Gpe Prix de vente",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"b\",\"Entity\":\"Factures\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"b\"}},\"Property\":\"PrixVente\"}}],\"BinItem\":{\"Expression\":{\"Member\":{\"Expression\":{\"Discretize\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"b\"}},\"Property\":\"PrixVente\"}},\"Count\":5}},\"Member\":\"Min\"}}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Factures\",\"TableItemName\":\"Gpe Prix de vente 2\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "expression": [
              "VAR __Count = 5",
              "",
              "VAR __Min = MIN('Factures'[PrixVente])",
              "",
              "VAR __Max = MAX('Factures'[PrixVente])",
              "",
              "VAR __Difference = (__Max - __Min)",
              "",
              "VAR __Size = IF(__Difference > 0, __Difference / __Count, 1)",
              "",
              "VAR __BinNumber = ",
              "  IF(",
              "    ISBLANK('Factures'[PrixVente]),",
              "    BLANK(),",
              "    ROUNDDOWN(('Factures'[PrixVente] - __Min) / __Size, 0)",
              "  )",
              "",
              "RETURN",
              "  IF(",
              "    ISBLANK('Factures'[PrixVente]),",
              "    BLANK(),",
              "    __Min + (MIN(__BinNumber, __Count - 1) * __Size)",
              "  )"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Factures"
                          }
                        },
                        "Property": "PrixVente"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "447ae2f2-e6b7-4bbc-9a77-c9d91f8c0b07",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Gpe Prix de vente 2",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"b\",\"Entity\":\"Factures\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"b\"}},\"Property\":\"Gpe Prix de vente\"}}],\"BinItem\":{\"Expression\":{\"Floor\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"b\"}},\"Property\":\"Gpe Prix de vente\"}},\"Size\":1.0}}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "expression": [
              "IF(",
              "  ISBLANK('Factures'[Gpe Prix de vente]),",
              "  BLANK(),",
              "  IF(",
              "    'Factures'[Gpe Prix de vente] >= 0,",
              "    ROUNDDOWN('Factures'[Gpe Prix de vente], 0),",
              "    ROUNDUP('Factures'[Gpe Prix de vente], 0)",
              "  )",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "binningMetadata": {
                    "binSize": {
                      "unit": 0,
                      "value": 1.0
                    }
                  },
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Factures"
                          }
                        },
                        "Property": "Gpe Prix de vente"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1ae0c18d-159b-4bbe-a002-caa9292ec71d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "DateCommande",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "65d3e379-bc0a-4b9a-a55a-018a9f318c12",
            "sourceColumn": "DateCommande",
            "summarizeBy": "none"
          },
          {
            "name": "CA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"fr-FR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "isHidden": true,
            "lineageTag": "c287d543-6dc3-4f07-bd41-c7dc14f1fd84",
            "sourceColumn": "CA",
            "summarizeBy": "sum"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "fa78db12-1576-4267-86ee-c52ae806dbde",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Marge Unitaire",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "0e730cea-76be-4f44-9a8f-37a7e84b58ce",
            "sourceColumn": "Marge Unitaire",
            "summarizeBy": "none"
          },
          {
            "name": "Groupe tx de marge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "if([% de marge] <0.3 , \"<30%\", if([% de marge] >0.4, \">40%\", \"30-40%\"))",
            "isDataTypeInferred": true,
            "lineageTag": "8a09adcd-b383-4a69-948c-04d3895ede80",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Grp tx marge",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "",
              "SWITCH( TRUE, ",
              "[Tx de marge] <0.2, \"<20%\", ",
              "[Tx de marge] <0.4, \"<40%\", ",
              "[Tx de marge] <0.6, \"<60%\", ",
              "\"+60%\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "5d5b05e8-df63-4865-bc9f-9f2917e08cf6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Plage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "if(Factures[DateFacture] >= max(Tempo[datemin]) && Factures[DateFacture] <= max(Tempo[datemax]), \"OK\", \"NOK\")",
            "isDataTypeInferred": true,
            "lineageTag": "22dc5931-2ed9-4d7b-8514-0c4e1c217045",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NumeroFacture (clusters)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"f\",\"Entity\":\"Factures\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"f\"}},\"Property\":\"NumeroFacture\"}}],\"PartitionTable\":{\"Definition\":{\"TableDefinition\":{\"Version\":2,\"From\":[{\"Name\":\"i\",\"Entity\":\"Indicateurs\"},{\"Name\":\"f\",\"Entity\":\"Factures\"}],\"Where\":[{\"Target\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"f\"}},\"Property\":\"NumeroFacture\"}}],\"Condition\":{\"Comparison\":{\"Left\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"i\"}},\"Property\":\"Tx de marge\"}},\"Right\":{\"Literal\":{\"Value\":\"0.4D\"}},\"ComparisonKind\":3}}}],\"OrderBy\":[],\"Select\":[{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"output0\"}},\"Property\":\"Factures.NumeroFacture\"},\"Name\":\"Factures.NumeroFacture\"},{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"output0\"}},\"Property\":\"clusterId\"},\"Name\":\"clusterId\"}],\"GroupBy\":[],\"Transform\":[{\"Name\":\"KMeansClustering\",\"Algorithm\":\"KMeansClustering\",\"Input\":{\"Parameters\":[{\"Literal\":{\"Value\":\"4L\"},\"Name\":\"NumberOfClusters\"}],\"Table\":{\"Name\":\"input0\",\"Columns\":[{\"Role\":\"Item\",\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"f\"}},\"Property\":\"NumeroFacture\"},\"Name\":\"Factures.NumeroFacture\"}},{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"i\"}},\"Property\":\"CA Total\"},\"Name\":\"Indicateurs.CA Total\"}},{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"i\"}},\"Property\":\"CA 30-40%\"},\"Name\":\"Indicateurs.CA 30-40%\"}},{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"i\"}},\"Property\":\"CA 30-40\"},\"Name\":\"Indicateurs.CA 30-40\"}},{\"Role\":\"Attribute\",\"Expression\":{\"Measure\":{\"Expression\":{\"SourceRef\":{\"Source\":\"i\"}},\"Property\":\"Tx de marge\"},\"Name\":\"Indicateurs.Tx de marge\"}}]}},\"Output\":{\"Table\":{\"Name\":\"output0\",\"Columns\":[{\"Expression\":{\"Column\":{\"Expression\":{\"TransformTableRef\":{\"Source\":\"input0\"}},\"Property\":\"Factures.NumeroFacture\"},\"Name\":\"Factures.NumeroFacture\"}},{\"Role\":\"Values\",\"Expression\":{\"TransformOutputRoleRef\":{\"Role\":\"ClusterId\"},\"Name\":\"clusterId\"}}]}}}]},\"ItemIdColumns\":[\"Factures.NumeroFacture\"],\"PartitionIdColumn\":\"clusterId\",\"Partitions\":[{\"PartitionIds\":[{\"Literal\":{\"Value\":\"null\"}}]}],\"DefaultPartitionPrefix\":\"Cluster\"},\"Result\":{\"TableName\":\"ClusterMappingTable 2\",\"PartitionIdColumn\":\"ClusterId\",\"ItemIdMappings\":[[{\"PartitionTableColumn\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Entity\":\"ClusterMappingTable 2\"}},\"Property\":\"NumeroFacture\"}},\"SourceTableColumn\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Entity\":\"Factures\"}},\"Property\":\"NumeroFacture\"}}}]]}}}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "description": "Clusters pour NumeroFacture",
            "expression": [
              "VAR __ClusterValue = ",
              "\tLOOKUPVALUE(",
              "\t\t'ClusterMappingTable 2'[ClusterId],",
              "\t\t'ClusterMappingTable 2'[NumeroFacture],",
              "\t\t'Factures'[NumeroFacture]",
              "\t)",
              "",
              "RETURN",
              "\tSWITCH(",
              "\t\t__ClusterValue,",
              "\t\tBLANK(),",
              "\t\tBLANK(),",
              "\t\tCONCATENATE(\"Cluster\", __ClusterValue)",
              "\t)"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "Factures"
                          }
                        },
                        "Property": "NumeroFacture"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "5f135c05-f36b-46c2-afb3-bc911d78c72a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "6d14a984-fde3-403a-8429-2e51a3d3ff67",
        "partitions": [
          {
            "name": "Factures-65ff2f70-1d4e-4f3e-8744-66cc4f0dcd86",
            "mode": "import",
            "queryGroup": "Table de faits",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(Source &\"\\Factures\\\"),",
                "    #\"Filtrer les fichiers 2020 & 2019\" = Table.SelectRows(Source, each ([Folder Path] <> \"C:\\Users\\Data Connection Ar\\Documents\\Data Connection\\Projets Clients\\Formation\\Power BI\\Modèle formation\\Documents formation Power BI\\Fichier demo\\Factures\\2021\\\")),",
                "    #\"Appeler une fonction personnalisée1\" = Table.AddColumn(#\"Filtrer les fichiers 2020 & 2019\", \"Transformer le fichier (2)\", each #\"Transformer le fichier (2)\"([Content])),",
                "    #\"Fichiers masqués filtrés2\" = Table.SelectRows(#\"Appeler une fonction personnalisée1\", each [Attributes]?[Hidden]? <> true),",
                "    #\"Autres colonnes supprimées2\" = Table.SelectColumns(#\"Fichiers masqués filtrés2\", {\"Transformer le fichier (2)\",\"Name\"}),",
                "    #\"Colonne de tables développée2\" = Table.ExpandTableColumn(#\"Autres colonnes supprimées2\", \"Transformer le fichier (2)\", Table.ColumnNames(#\"Transformer le fichier (2)\"(#\"Exemple de fichier (2)\"))),",
                "    #\"Type modifié1\" = Table.TransformColumnTypes(#\"Colonne de tables développée2\",{{\"NumeroFacture\", type text}, {\"ProduitId\", type text}, {\"ClientId\", type text}, {\"DateFacture\", type date}, {\"Quantite\", Int64.Type}, {\"PrixVente\", type number}, {\"PrixAchat\", type number}, {\"ID\", Int64.Type}, {\"TotalVente\", Currency.Type}, {\"DateCommande\", type date}}),",
                "    #\"Autres colonnes supprimées\" = Table.SelectColumns(#\"Type modifié1\",{\"NumeroFacture\", \"ProduitId\", \"ClientId\", \"DateFacture\", \"DateCommande\", \"Quantite\", \"PrixVente\", \"PrixAchat\", \"ID\", \"TotalVente\", \"Name\"}),",
                "    #\"Ajout Facture 2021\" = Table.Combine({#\"Autres colonnes supprimées\", #\"Factures 2021\"}),",
                "    #\"Fusion Table Client\" = Table.NestedJoin(#\"Ajout Facture 2021\", {\"ClientId\"}, Client, {\"ClientId\"}, \"Client\", JoinKind.RightOuter),",
                "    #\"Client.Ville développé\" = Table.ExpandTableColumn(#\"Fusion Table Client\", \"Client\", {\"Ville\"}, {\"Ville\"}),",
                "    #\"Calcul Marge Unitaire\" = Table.AddColumn(#\"Client.Ville développé\", \"Marge Unitaire\", each [PrixVente] - [PrixAchat], type number),",
                "    #\"Renommer Total CA\" = Table.RenameColumns(#\"Calcul Marge Unitaire\",{{\"TotalVente\", \"CA\"}}),",
                "    #\"Filtre CA <> 0\" = Table.SelectRows(#\"Renommer Total CA\", each ([CA] <> 0))",
                "in",
                "    #\"Filtre CA <> 0\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Calendrier",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "112c1736-2460-4902-91cf-96be0b3e4aad"
          },
          {
            "name": "LinkedQueryName",
            "value": "Date"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":11,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Date/Type modifié.{Column1,0}\",\"Section1/Date/Année insérée.{Année,1}\",\"Section1/Date/Début de mois inséré.{Début de mois,2}\",\"Section1/Date/Fin de mois insérée.{Fin du mois,3}\",\"Section1/Date/Jour de la semaine inséré.{Jour de la semaine,4}\",\"Section1/Date/Nom du jour inséré.{Nom du jour,5}\",\"Section1/Date/Type modifié1.{Ouvrés / Fériés,6}\",\"Section1/Date/Colonne fusionnée insérée.{Trimestre Année,9}\",\"Section1/Date/Mois inséré.{Mois,8}\",\"Section1/Date/Nom du mois inséré.{Nom du mois,9}\",\"Section1/Date/Trimestre inséré1.{Trimestre,10}\"],\"ColumnCount\":11,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Date/Type modifié.{Column1,0}\",\"Section1/Date/Année insérée.{Année,1}\",\"Section1/Date/Début de mois inséré.{Début de mois,2}\",\"Section1/Date/Fin de mois insérée.{Fin du mois,3}\",\"Section1/Date/Jour de la semaine inséré.{Jour de la semaine,4}\",\"Section1/Date/Nom du jour inséré.{Nom du jour,5}\",\"Section1/Date/Type modifié1.{Ouvrés / Fériés,6}\",\"Section1/Date/Colonne fusionnée insérée.{Trimestre Année,9}\",\"Section1/Date/Mois inséré.{Mois,8}\",\"Section1/Date/Nom du mois inséré.{Nom du mois,9}\",\"Section1/Date/Trimestre inséré1.{Trimestre,10}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "Date Calendrier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "182c5c09-9883-4832-b290-a8557732d0dc",
            "sourceColumn": "Date Calendrier",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hiérarchie de dates",
                  "table": "LocalDateTable_a5c14128-44b1-489a-af52-976aaf8e8bef"
                },
                "isDefault": true,
                "relationship": "6be7be36-c40b-4336-843e-a22dd0c08626"
              }
            ]
          },
          {
            "name": "Année",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8a2baeda-0fac-46f2-b23c-6f84ffa53b73",
            "sourceColumn": "Année",
            "summarizeBy": "none"
          },
          {
            "name": "Début de mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mmmm yyyy",
            "lineageTag": "e17d920d-93e8-4686-9e29-001471f4bf80",
            "sourceColumn": "Début de mois",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hiérarchie de dates",
                  "table": "LocalDateTable_0bfa5a34-2fb2-43a4-9984-56c5a1d790dc"
                },
                "isDefault": true,
                "relationship": "594267df-fd47-42b3-b5d7-47c964afbd4e"
              }
            ]
          },
          {
            "name": "Fin du mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "23f5f928-b3e2-45f7-b8a3-be7f8e46e6f3",
            "sourceColumn": "Fin du mois",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hiérarchie de dates",
                  "table": "LocalDateTable_760eb492-0002-4761-bf71-1350a2012588"
                },
                "isDefault": true,
                "relationship": "ea0e86a0-ef1a-46b2-98dd-d2e3a4d4aa3e"
              }
            ]
          },
          {
            "name": "Jour de la semaine",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bdbb9511-3bc8-4dc4-92e4-18120ea2e494",
            "sourceColumn": "Jour de la semaine",
            "summarizeBy": "none"
          },
          {
            "name": "Nom du jour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a17f71e3-6d6f-421b-856a-7250bec0c10d",
            "sourceColumn": "Nom du jour",
            "summarizeBy": "none"
          },
          {
            "name": "Ouvrés / Fériés",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b78a00a-6e24-4fac-8ece-6233852979a7",
            "sourceColumn": "Ouvrés / Fériés",
            "summarizeBy": "none"
          },
          {
            "name": "Trimestre Année",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "035df377-ce2d-4def-bf87-1e15968bfec9",
            "sortByColumn": "Année",
            "sourceColumn": "Trimestre Année",
            "summarizeBy": "none"
          },
          {
            "name": "N° de Mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "24c98144-2b0b-4d0d-9986-844a661c4b75",
            "sourceColumn": "N° de Mois",
            "summarizeBy": "none"
          },
          {
            "name": "Nom du mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c68e5348-a0bd-46e8-beff-01cf0d76b318",
            "sortByColumn": "N° de Mois",
            "sourceColumn": "Nom du mois",
            "summarizeBy": "none"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "07525f7f-e314-42b7-ad7d-247434371cf5",
            "sourceColumn": "Trimestre",
            "summarizeBy": "none"
          },
          {
            "name": "date -12 mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "",
              "",
              "var moisCalcule = IF(Calendrier[N° de Mois] = 12, 1, -1)",
              "var anneeCalcule = IF(Calendrier[N° de Mois] = 12, Calendrier[Année], -1)",
              "",
              "return  CALCULATE(DATEADD(Calendrier[Début de mois], -11, MONTH))",
              "",
              ""
            ],
            "formatString": "Long Date",
            "isDataTypeInferred": true,
            "lineageTag": "15c2f7d5-97c5-4b66-9987-75f6dffd4a67",
            "summarizeBy": "none",
            "type": "calculated",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hiérarchie de dates",
                  "table": "LocalDateTable_4d7274eb-a370-43df-a354-1ee0cc1dda27"
                },
                "isDefault": true,
                "relationship": "80f57377-2dd2-41f2-8299-fe080cfeb2ae"
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarchie Chronologique",
            "levels": [
              {
                "name": "Année",
                "column": "Année",
                "lineageTag": "a8ebe66b-179b-4304-9fae-c8542f0c381e",
                "ordinal": 0
              },
              {
                "name": "Trimestre Année",
                "column": "Trimestre Année",
                "lineageTag": "31c72ae9-1b58-4c18-8c99-fdd9ffd0ae08",
                "ordinal": 1
              },
              {
                "name": "Début de mois",
                "column": "Début de mois",
                "lineageTag": "1551d63f-ef16-47a8-83a8-f8b5dd96e172",
                "ordinal": 2
              },
              {
                "name": "Date Calendrier",
                "column": "Date Calendrier",
                "lineageTag": "daa395b1-a687-46ca-9c74-2c9d12002b0f",
                "ordinal": 3
              }
            ],
            "lineageTag": "62b3c75e-b7b4-4542-871c-ae26a27b288a"
          }
        ],
        "lineageTag": "469bf6ad-00a7-4a58-9cac-cfbb8b8bff7a",
        "partitions": [
          {
            "name": "Calendrier-99d422bf-0fa7-4da9-9838-f747a45f5dac",
            "mode": "import",
            "queryGroup": "Tables de dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = \"\",",
                "    #\"Ecart en nombre\" = {43101..48000},",
                "    #\"Converti en table\" = Table.FromList(#\"Ecart en nombre\", Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"Converti en table\",{{\"Column1\", type date}}),",
                "    #\"Date Calendrier Renommé\" = Table.RenameColumns(#\"Type modifié\",{{\"Column1\", \"Date Calendrier\"}}),",
                "    #\"Année insérée\" = Table.AddColumn(#\"Date Calendrier Renommé\", \"Année\", each Date.Year([Date Calendrier]), Int64.Type),",
                "    #\"Début de mois inséré\" = Table.AddColumn(#\"Année insérée\", \"Début de mois\", each Date.StartOfMonth([Date Calendrier]), type date),",
                "    #\"Fin de mois insérée\" = Table.AddColumn(#\"Début de mois inséré\", \"Fin du mois\", each Date.EndOfMonth([Date Calendrier]), type date),",
                "    #\"Jour de la semaine inséré\" = Table.AddColumn(#\"Fin de mois insérée\", \"Jour de la semaine\", each Date.DayOfWeek([Date Calendrier]), Int64.Type),",
                "    #\"Nom du jour inséré\" = Table.AddColumn(#\"Jour de la semaine inséré\", \"Nom du jour\", each Date.DayOfWeekName([Date Calendrier]), type text),",
                "    #\"Col. Cond. Jour Fériés\" = Table.AddColumn(#\"Nom du jour inséré\", \"Ouvrés / Fériés\", each if [Jour de la semaine] <= 4 then \"Ouvrés\" else \"Fériés\"),",
                "    #\"Trimestre inséré\" = Table.AddColumn(#\"Col. Cond. Jour Fériés\", \"Trimestre\", each Date.QuarterOfYear([Date Calendrier]), Int64.Type),",
                "    #\"Ajout Col. Tri\" = Table.AddColumn(#\"Trimestre inséré\", \"Personnalisé\", each \"Tri\"),",
                "    #\"Filtre 2021 2020 2019\" = Table.SelectRows(#\"Ajout Col. Tri\", each ([Année] = 2022 or [Année] = 2020 or [Année] = 2021)),",
                "    #\"Création Tri Année\" = Table.AddColumn(#\"Filtre 2021 2020 2019\", \"Trimestre Année\", each Text.Combine({[Personnalisé], Text.From([Trimestre], \"fr-FR\"), Text.From([Année], \"fr-FR\")}, \" \"), type text),",
                "    #\"Supprimé Tri\" = Table.RemoveColumns(#\"Création Tri Année\",{\"Trimestre\", \"Personnalisé\"}),",
                "    #\"Type modifié1\" = Table.TransformColumnTypes(#\"Supprimé Tri\",{{\"Ouvrés / Fériés\", type text}}),",
                "    #\"Mois inséré\" = Table.AddColumn(#\"Type modifié1\", \"Mois\", each Date.Month([Date Calendrier]), Int64.Type),",
                "    #\"Nom du mois inséré\" = Table.AddColumn(#\"Mois inséré\", \"Nom du mois\", each Date.MonthName([Date Calendrier]), type text),",
                "    #\"Trimestre inséré1\" = Table.AddColumn(#\"Nom du mois inséré\", \"Trimestre\", each Date.QuarterOfYear([Date Calendrier]), Int64.Type),",
                "    #\"N° Mois renommé\" = Table.RenameColumns(#\"Trimestre inséré1\",{{\"Mois\", \"N° de Mois\"}}),",
                "    #\"Filtrer sur le dernier jour ouvré\" = Table.SelectRows(#\"N° Mois renommé\", each [Date Calendrier] <= #\"Dernier jour Ouvré Facturation\")",
                "in",
                "    #\"Filtrer sur le dernier jour ouvré\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a5c14128-44b1-489a-af52-976aaf8e8bef",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "605be88a-5faa-49bc-9406-661e584398bd",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Année",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "79a824f2-88e0-40a2-82b5-2e60ab8d62aa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoMois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6e37d138-ad27-4ebc-af90-fb2e802bcbfb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "56baf2f4-5e8d-4188-8462-ea776d36d280",
            "sortByColumn": "NoMois",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NoMois] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6ce26778-2764-4fe6-8cdd-1d0963f4b26e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [NoTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0c77d196-63d9-4e13-8a7b-385b422822af",
            "sortByColumn": "NoTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Jour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0de070c6-e314-4f82-b752-6087628b18d4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Année",
                "column": "Année",
                "lineageTag": "8e9c8ada-970e-41fc-a15f-d43b74b4b222",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "2c1faff2-d6ca-4034-b847-8127b8691dfc",
                "ordinal": 1
              },
              {
                "name": "Mois",
                "column": "Mois",
                "lineageTag": "681c19e6-96f6-4a9d-8524-8ff82e490681",
                "ordinal": 2
              },
              {
                "name": "Jour",
                "column": "Jour",
                "lineageTag": "34b2fa23-f792-4f10-a978-6f9a656041d0",
                "ordinal": 3
              }
            ],
            "lineageTag": "29a2444c-f002-4505-a367-40b265f177ab"
          }
        ],
        "isHidden": true,
        "lineageTag": "18617274-eb2a-4593-8854-9c3e300c6720",
        "partitions": [
          {
            "name": "LocalDateTable_a5c14128-44b1-489a-af52-976aaf8e8bef-0baac5bd-b690-4007-b67e-03c7587795b8",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendrier'[Date Calendrier])), 1, 1), Date(Year(MAX('Calendrier'[Date Calendrier])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_0bfa5a34-2fb2-43a4-9984-56c5a1d790dc",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e51447d9-f8e4-485e-a548-106be6298365",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Année",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "75f445cb-e939-42be-8aed-c8c7af0a63db",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoMois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5f09f402-89eb-40fb-a750-5641b8694579",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a79f7c2f-19bb-4979-944b-bbe238fca32d",
            "sortByColumn": "NoMois",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NoMois] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c948a0f8-fae9-4acf-9ef3-0ad4ab0d768f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [NoTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f99a4a7b-15c0-4eff-9d8a-f24a0d29a268",
            "sortByColumn": "NoTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Jour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "84b34a4f-094b-4319-b75c-08fef3bcae52",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Année",
                "column": "Année",
                "lineageTag": "c048b71e-093f-4abb-a522-ee9017143bce",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "b705ee1a-6ecc-4a14-8f9b-ef527feffe68",
                "ordinal": 1
              },
              {
                "name": "Mois",
                "column": "Mois",
                "lineageTag": "39a2bccc-fe72-47a0-8844-3a6f95c90c23",
                "ordinal": 2
              },
              {
                "name": "Jour",
                "column": "Jour",
                "lineageTag": "958b6535-eab9-4849-a9cb-2ecac8e52143",
                "ordinal": 3
              }
            ],
            "lineageTag": "d7432f28-29bc-4969-95db-763b4309dbe6"
          }
        ],
        "isHidden": true,
        "lineageTag": "1f6f385d-d475-4bab-9d82-9ef22875f567",
        "partitions": [
          {
            "name": "LocalDateTable_0bfa5a34-2fb2-43a4-9984-56c5a1d790dc-dd926ab0-52e3-482f-b5f5-56f2fc1cb07c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendrier'[Début de mois])), 1, 1), Date(Year(MAX('Calendrier'[Début de mois])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_760eb492-0002-4761-bf71-1350a2012588",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cd05e0c2-7ff5-442e-854c-a0fd03eedf13",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Année",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "58f31abc-bf97-47e3-a790-7ac538b46cb7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoMois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cf86c9bf-ebd1-43c6-b7ba-ad2c7caaa69e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6ddf7115-325f-4b28-9973-db8d91a5c8c0",
            "sortByColumn": "NoMois",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NoMois] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "86705b5f-55a3-4446-8701-45f6cb7523d0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [NoTrimestre]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c56eb454-8cd7-41e6-8b92-825ef08540a9",
            "sortByColumn": "NoTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Jour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6c8c9f25-2616-41b5-9bc9-d81dd21754d1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Année",
                "column": "Année",
                "lineageTag": "f04a958f-2232-481f-a802-968fe7941ef5",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "3c62a1d0-460f-4bd6-ab81-ccd99df901f0",
                "ordinal": 1
              },
              {
                "name": "Mois",
                "column": "Mois",
                "lineageTag": "b263398e-08dc-4dd2-a3a9-fd7d58f08fd4",
                "ordinal": 2
              },
              {
                "name": "Jour",
                "column": "Jour",
                "lineageTag": "2ae53cb2-d366-4bb9-880c-039c46d01ecb",
                "ordinal": 3
              }
            ],
            "lineageTag": "f20f3449-4a2f-4350-9479-fd32505d73aa"
          }
        ],
        "isHidden": true,
        "lineageTag": "25558f54-2fe9-4908-bf94-61c74634bfd8",
        "partitions": [
          {
            "name": "LocalDateTable_760eb492-0002-4761-bf71-1350a2012588-54a19bfe-f482-4b91-b19f-b9bf00e4a74b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendrier'[Fin du mois])), 1, 1), Date(Year(MAX('Calendrier'[Fin du mois])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Indicateurs",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "be775269-fdf3-42bc-8b34-e7b1a403ff97"
          },
          {
            "name": "LinkedQueryName",
            "value": "Indicateurs"
          },
          {
            "name": "PBI_QueryRelationships",
            "value": "{\"columnCount\":1,\"keyColumnNames\":[],\"queryRelationships\":[],\"columnIdentities\":[\"Section1/Indicateurs/Type modifié.{Colonne 1,0}\"],\"ColumnCount\":1,\"KeyColumnNames\":[],\"ColumnIdentities\":[\"Section1/Indicateurs/Type modifié.{Colonne 1,0}\"],\"RelationshipInfo\":[]}"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "__PBI_SemanticLinks",
            "value": "[{\"LinkTarget\":{\"TableName\":\"Produits\",\"TableItemName\":\"NomProduit (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"},{\"LinkTarget\":{\"TableName\":\"Factures\",\"TableItemName\":\"NumeroFacture (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Colonne 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "displayFolder": "Autres trucs",
            "isHidden": true,
            "lineageTag": "0d6900e6-b26c-4d38-8489-73f57158e3d9",
            "sourceColumn": "Colonne 1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3a400b48-2246-43da-8ca6-2be8bff89741",
        "measures": [
          {
            "name": "Marge totale",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "Calcul de la marge",
              "(CA Total - Prix d'achat x quantité) basé sur la date de facture",
              "SUM ( 'Base Facturation'[Marge Total] )"
            ],
            "displayFolder": "Autres trucs",
            "expression": "SUM ( 'Factures'[Marge] )",
            "formatString": "#,0",
            "lineageTag": "b52e963f-3fab-4126-bfb6-223e7385f718"
          },
          {
            "name": "Marge Hyper",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": [
              "CALCULATE (",
              "    SUM ( 'Base Facturation'[Marge Total] ),",
              "    FILTER ( ALL ( Client[Nature] ), Client[Nature] = \"Hyper\" )",
              ")"
            ],
            "displayFolder": "Trucs mesures",
            "expression": [
              "CALCULATE (",
              "    SUM ( 'Factures'[Marge] ),",
              "    FILTER ( ALL ( Client[Nature] ), Client[Nature] = \"Hyper\" )",
              ")"
            ],
            "isHidden": true,
            "lineageTag": "3d420587-4079-467f-82c8-d225fc7878ce"
          },
          {
            "name": "CA Cditment 1000",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"fr-FR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": [
              "CALCULATE (",
              "    [CA Total],",
              "    KEEPFILTERS ( Produits[Conditionnement] >= 1000 ),",
              "    REMOVEFILTERS ( Commerciaux[NomCommercial] )",
              ")"
            ],
            "displayFolder": "Trucs mesures",
            "expression": [
              "CALCULATE (",
              "    [CA Total],",
              "    KEEPFILTERS ( Produits[Conditionnement] >= 1000 ),",
              "    REMOVEFILTERS ( Commerciaux[NomCommercial] )",
              ")"
            ],
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "isHidden": true,
            "lineageTag": "a25e8c01-34f0-4e59-861b-edb481b3ef72"
          },
          {
            "name": "CA Total",
            "annotations": [
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Produits\",\"TableItemName\":\"NomProduit (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"},{\"LinkTarget\":{\"TableName\":\"Factures\",\"TableItemName\":\"NumeroFacture (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "Calcul du chiffre d'affaire basé sur la date de facture",
              "SUM ( 'Base Facturation'[Total CA] )"
            ],
            "displayFolder": "Autres trucs",
            "expression": "SUM ( 'Factures'[CA] )",
            "formatString": "#,0",
            "lineageTag": "0e42c110-2e42-4fab-a728-9315a148d922"
          },
          {
            "name": "CA Paul Derwin et Luc Albert",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "description": [
              "CALCULATE (",
              "    [CA Total],",
              "    Commerciaux[NomCommercial] = \"Paul Derwin\"",
              "        || Commerciaux[NomCommercial] = \"Luc Albert\"",
              ")"
            ],
            "displayFolder": "Trucs mesures",
            "expression": [
              "CALCULATE (",
              "    [CA Total],",
              "    Commerciaux[NomCommercial] = \"Paul Derwin\"",
              "        || Commerciaux[NomCommercial] = \"Luc Albert\"",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "c6850887-f175-4106-9f3b-c578683a347e"
          },
          {
            "name": "CA PD et LA 2019",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "description": "CALCULATE ( [CA Paul Derwin et Luc Albert], 'Date'[Année] = 2019 )",
            "displayFolder": "Trucs mesures",
            "expression": "CALCULATE ( [CA Paul Derwin et Luc Albert], 'Calendrier'[Année] = 2019 )",
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "2cca544d-9600-449a-8176-6192835cd07a"
          },
          {
            "name": "CA Fév à Aout",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "description": "CALCULATE ( [CA Total], 'Date'[N° de Mois] >= 2 && 'Date'[N° de Mois] <= 8 )",
            "displayFolder": "Temps",
            "expression": "CALCULATE ( [CA Total], 'Calendrier'[N° de Mois] >= 2 && 'Calendrier'[N° de Mois] <= 8 )",
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "5fd8e6fe-d37c-4836-aacc-20863addbe5c"
          },
          {
            "name": "CA M-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "Résultat du mois précédent",
              "CALCULATE ( [CA Total], PREVIOUSMONTH ( 'Date'[Date Calendrier] ) )"
            ],
            "displayFolder": "Temps",
            "expression": "CALCULATE ( [CA Total], PREVIOUSMONTH ( 'Calendrier'[Date Calendrier] ) )",
            "formatString": "#,0",
            "lineageTag": "1ec4c1cd-e188-4468-9b6a-e8c2e29165b2"
          },
          {
            "name": "CA M-2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "Résultat du 2eme derniers mois",
              "CALCULATE ( [CA Total], DATEADD ( 'Date'[Date Calendrier], -2, MONTH ) )"
            ],
            "displayFolder": "Temps",
            "expression": "CALCULATE ( [CA Total], DATEADD ( 'Calendrier'[Date Calendrier], -2, MONTH ) )",
            "formatString": "#,0",
            "lineageTag": "9cc41563-a309-48ab-9bad-177010ed68fb"
          },
          {
            "name": "CA N-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "CA de l'année dernière précedente",
              "CALCULATE ( [CA Total], SAMEPERIODLASTYEAR ( 'Date'[Date Calendrier] ) )"
            ],
            "displayFolder": "Temps",
            "expression": "CALCULATE ( [CA Total], SAMEPERIODLASTYEAR ( 'Calendrier'[Date Calendrier] ) )",
            "formatString": "#,0",
            "lineageTag": "32f684ff-41ac-4ca8-b06c-4cfc10370f36"
          },
          {
            "name": "Panier Moyen Client",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"fr-FR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": [
              "Montant moyen facturé par enseigne",
              "AVERAGEX ( VALUES ( Client[Enseigne] ), [CA Total] )"
            ],
            "displayFolder": "Autres trucs",
            "expression": "AVERAGEX ( VALUES ( Client[Enseigne] ), [CA Total] )",
            "formatString": "#,0\\ \"€\";-#,0\\ \"€\";#,0\\ \"€\"",
            "lineageTag": "c3a0de4b-0d39-4058-a48f-4c099efc4f79"
          },
          {
            "name": "Tx de marge",
            "annotations": [
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Produits\",\"TableItemName\":\"NomProduit (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"},{\"LinkTarget\":{\"TableName\":\"Factures\",\"TableItemName\":\"NumeroFacture (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              },
              {
                "property": "FormatString"
              }
            ],
            "description": "SUM ( 'Base Facturation'[Marge Total] ) / SUM ( 'Base Facturation'[Total CA] )",
            "displayFolder": "Autres trucs",
            "expression": "DIVIDE([Marge totale],[CA Total])",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "d69d3397-67ed-4647-8788-01b5d56de58f"
          },
          {
            "name": "CA YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "Résultat cumulé",
              "CALCULATE ( [CA Total], DATESYTD ( 'Date'[Date Calendrier] ) )"
            ],
            "displayFolder": "Temps",
            "expression": "CALCULATE ( [CA Total], DATESYTD ( 'Calendrier'[Date Calendrier] ) )",
            "formatString": "#,0",
            "lineageTag": "3687a001-afe7-4224-b50c-1bd6676589e4"
          },
          {
            "name": "CA N-1  Total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "Résultat l'année dernière à la même période",
              "CALCULATE ( [CA Total], PARALLELPERIOD ( 'Date'[Date Calendrier], -1, YEAR ) )"
            ],
            "displayFolder": "Temps",
            "expression": "CALCULATE ( [CA Total], PARALLELPERIOD ( 'Calendrier'[Date Calendrier], -1, YEAR ) )",
            "formatString": "#,0",
            "lineageTag": "32ec7d1d-4dc6-444c-8cc7-8719fd8e44ec"
          },
          {
            "name": "CA M vs M-1",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "Variation mensuelle entre le mois actuel et le mois précédent",
              "DIVIDE ( ( [CA Total] - [CA M-1] ), [CA M-1] )"
            ],
            "displayFolder": "Temps",
            "expression": "DIVIDE ( ( [CA Total] - [CA M-1] ), [CA M-1] )",
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "3c5a84c7-db7d-4bd3-881b-fc24b119359a"
          },
          {
            "name": "Sumx",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"fr-FR\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "SUMX ( FILTER ( Produits, Produits[Conditionnement] >= 1000 ), [CA Total] )",
            "displayFolder": "Trucs mesures",
            "expression": "SUMX ( FILTER ( Produits, Produits[Conditionnement] >= 1000 ), [CA Total] )",
            "formatString": "#,0.###############\\ \"€\";-#,0.###############\\ \"€\";#,0.###############\\ \"€\"",
            "isHidden": true,
            "lineageTag": "55eaf2a0-1f96-476d-8763-18b47368b640"
          },
          {
            "name": "CA N vs N-1",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "Variation annuelle entre la période actuelle et de la même période de l'année dernière.",
              "DIVIDE ( ( [CA Total] - [CA M N-1] ), [CA M N-1] )"
            ],
            "displayFolder": "Temps",
            "expression": "DIVIDE ( ( [CA Total] - [CA N-1] ), [CA N-1] )",
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "08ed595a-06ac-49a3-a88e-a6d0d99f5426"
          },
          {
            "name": "CA N-1 YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "Résultat cumulé de l'année précédente",
              "CALCULATE ( [CA M N-1], DATESYTD ( 'Date'[Date Calendrier] ) )"
            ],
            "displayFolder": "Temps",
            "expression": "CALCULATE ( [CA N-1], DATESYTD ( 'Calendrier'[Date Calendrier] ) )",
            "lineageTag": "4f01186c-c338-4e28-8bae-4b24cf1099b8"
          },
          {
            "name": "Budget",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "Montant budgété 2020 - 2021",
              "SUM ( Budget[Montant] )"
            ],
            "displayFolder": "Autres trucs",
            "expression": "SUM ( Budget[Montant] )",
            "formatString": "#,0",
            "lineageTag": "c5a76c5d-9631-4d80-ab83-ce4ce1a458d1"
          },
          {
            "name": "Var Budg.",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "DIVIDE ( ( [CA Total] - [Budget] ), [Budget] )",
            "displayFolder": "Autres trucs",
            "expression": "DIVIDE ( ( [CA Total] - [Budget] ), [Budget] )",
            "formatString": "0\\ %;-0\\ %;0\\ %",
            "lineageTag": "e491b278-1271-42dd-a6f3-2c343754cf66"
          },
          {
            "name": "CA Date de commande",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "description": [
              "Calcul du chiffre d'affaire basé sur la date de commande",
              "CALCULATE([CA Total],USERELATIONSHIP('Base Facturation'[DateCommande],'Date'[Date Calendrier]))"
            ],
            "displayFolder": "Autres trucs",
            "expression": "CALCULATE([CA Total],USERELATIONSHIP('Factures'[DateCommande],'Calendrier'[Date Calendrier]))",
            "lineageTag": "4c611d78-1768-434b-8998-69f086c695c2"
          },
          {
            "name": "Max année",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Temps",
            "expression": "CONCATENATE(\"CA de l'année \",max('Calendrier'[Année]))",
            "lineageTag": "4e3012ea-de21-4ba3-b850-fb6c483bceec"
          },
          {
            "name": "TitreDétailsCourbe",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Titres",
            "expression": "IF(LOWER(min('Sous famille'[SousFamille])) = \"Agrumes\", \"Vente d'\"&LOWER(min('Sous famille'[SousFamille]))&\" selon les mois et les années\", \"Vente de \"&lower(min('Sous famille'[SousFamille]))&\" selon les mois et les années\")",
            "lineageTag": "3f39201d-c569-4415-b49e-a56aa0243502"
          },
          {
            "name": "TitreDétailsCommerciaux",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Titres",
            "expression": "\"Chiffre d'affaires et marge des \"&LOWER(min('Sous famille'[SousFamille]))&\" par commercial\"",
            "lineageTag": "d99397fe-9400-4dca-8523-1914beaeb14d"
          },
          {
            "name": "CAAllCommerciaux",
            "expression": "CALCULATE(SUM(Factures[CA]), ALL(Commerciaux[NomCommercial]))",
            "formatString": "#,0.00\\ \"€\";-#,0.00\\ \"€\";#,0.00\\ \"€\"",
            "lineageTag": "31418f25-ca44-4431-9230-23b94e3fee0e"
          },
          {
            "name": "Pourcentage Commercial CA",
            "expression": "DIVIDE([CA Total], [CAAllCommerciaux])",
            "formatString": "0.00\\ %;-0.00\\ %;0.00\\ %",
            "lineageTag": "9a6cac59-fe08-47fb-a2e6-acc16c3af2e2"
          },
          {
            "name": "Ca YTD manuel",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Temps",
            "expression": "CALCULATE([CA Total],  FILTER( ALL(Calendrier), Calendrier[Année] = MAX(Calendrier[Année]) && Calendrier[N° de Mois]<= MAX(Calendrier[N° de Mois])))",
            "lineageTag": "a0c51355-664e-4496-8890-e2076c72cb7e"
          },
          {
            "name": "Date - 12 mois",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([CA Total], FILTER(ALL(Calendrier), Calendrier[Début de mois] >= MAX(Calendrier[date -12 mois]) && Calendrier[Date Calendrier] <= MAX(Calendrier[Date Calendrier])))",
            "lineageTag": "937a13e4-f69f-44ed-9d32-98fddd6eb46c"
          },
          {
            "name": "CA 30-40%",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Factures\",\"TableItemName\":\"NumeroFacture (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "expression": "CALCULATE([CA Total], FILTER(Factures, Factures[Groupe tx de marge] = \"30-40%\"))",
            "lineageTag": "d1a385b8-879a-48d8-a938-8bf467268ed6"
          },
          {
            "name": "CA 30-40",
            "annotations": [
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Factures\",\"TableItemName\":\"NumeroFacture (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "displayFolder": "Autres trucs",
            "expression": "CALCULATE([CA Total], FILTER(VALUES(Factures[NumeroFacture]), [Tx de marge] >=0.30 && [Tx de marge]<=0.40))",
            "formatString": "#,0.00",
            "lineageTag": "0edde9d3-127e-4957-9392-86d9ed8b9e89"
          },
          {
            "name": "CA date commande",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([CA Total], USERELATIONSHIP(Factures[DateCommande],Calendrier[Date Calendrier]))",
            "lineageTag": "912c73e4-3077-4754-ba38-0ae251ce5ef9"
          },
          {
            "name": "Tx marge comm",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "AVERAGEX(Commerciaux, [Tx de marge])",
            "lineageTag": "0fa8608f-ae17-4b26-9c7b-d6872ecde7d4"
          },
          {
            "name": "Mesure",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "813bd07c-dd44-4dd7-be57-8c60492c7300"
          },
          {
            "name": "tx marge commerciaux test",
            "lineageTag": "819a2265-e85f-4433-8d6e-005fdecf8dda"
          },
          {
            "name": "Nb clients commercial",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "if(COUNTROWS(Commerciaux) = 1,",
              "CALCULATE(DISTINCTCOUNT(Client[ClientId]), FILTER(Client, Client[IcId] = MAX(Commerciaux[IcId]))), ",
              "DISTINCTCOUNT(Client[ClientId]))"
            ],
            "lineageTag": "fc75ccab-7c70-450d-8fdf-3af7164b5e31"
          },
          {
            "name": "Mesure 2",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "3b6bbeb8-6368-4d52-83bd-3db8c0257cad"
          },
          {
            "name": "SF sel",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "if(COUNTROWS('Sous famille') = 1, VALUES('Sous famille'[SousFamille]), \"\")",
              "",
              "",
              ""
            ],
            "lineageTag": "462d8afe-8c96-4f6a-bb8a-39e575a9c22b"
          }
        ],
        "partitions": [
          {
            "name": "Indicateurs-9425551f-e497-483e-bbf9-0152d33ea2fe",
            "mode": "import",
            "queryGroup": "Tables de dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [#\"Colonne 1\" = _t]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(Source,{{\"Colonne 1\", type text}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ClusterMappingTable",
        "annotations": [
          {
            "name": "ClusterMappingTable",
            "value": "true"
          },
          {
            "name": "__PBI_SemanticLinks",
            "value": "[{\"LinkTarget\":{\"TableName\":\"Produits\",\"TableItemName\":\"NomProduit (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
          }
        ],
        "columns": [
          {
            "name": "NomProduit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Produits\",\"TableItemName\":\"NomProduit (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "074c61aa-8a53-4b4c-89a5-209c700f6ddf",
            "sourceColumn": "[NomProduit]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ClusterId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Produits\",\"TableItemName\":\"NomProduit (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d5ac7e01-43ba-46a8-a25a-5d6658fb7f5f",
            "sourceColumn": "[ClusterId]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "f05f9e54-face-40a6-b871-8170f099c8dc",
        "partitions": [
          {
            "name": "ClusterMappingTable-56660cb9-9c2a-4186-9686-373af9d350a1",
            "mode": "import",
            "source": {
              "expression": [
                "VAR __DS0BodyPreTransform = ",
                "  SUMMARIZECOLUMNS(",
                "    'Produits'[NomProduit],",
                "    \"CA_Total\", 'Indicateurs'[CA Total],",
                "    \"Tx_de_marge\", 'Indicateurs'[Tx de marge]",
                "  )",
                "",
                "VAR __DataTransformT0 = ",
                "  KMeansClustering(",
                "    SELECTCOLUMNS(",
                "      __DS0BodyPreTransform,",
                "      \"NomProduit\", 'Produits'[NomProduit],",
                "      \"CA_Total\", [CA_Total],",
                "      \"Tx_de_marge\", [Tx_de_marge]",
                "    ),",
                "    {(\"[CA_Total]\", \"Attribute\"),",
                "      (\"[Tx_de_marge]\", \"Attribute\"),",
                "      (\"[NomProduit]\", \"Item\")},",
                "    {(\"[NomProduit]\", BLANK()),",
                "      (\"ClusterId\", \"ClusterId\")},",
                "    5",
                "  )",
                "",
                "RETURN __DataTransformT0"
              ],
              "retainDataTillForceCalculate": true,
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Sous famille",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SousFamilleId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f77b62f5-f10d-49ac-a2c5-0e3c76ec9dc5",
            "sourceColumn": "SousFamilleId",
            "summarizeBy": "none"
          },
          {
            "name": "SousFamille",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3defde3b-a50d-4a1b-a61d-94f889efd7c3",
            "sourceColumn": "SousFamille",
            "summarizeBy": "none"
          },
          {
            "name": "Famille",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35ad6ff3-3861-4dac-a456-9ec70b615a1f",
            "sourceColumn": "Famille",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c4e971c5-b947-4654-9aad-13d960b89eee",
        "partitions": [
          {
            "name": "Sous famille-e5270604-76b5-47e0-843a-62d5128927c8",
            "mode": "import",
            "queryGroup": "Tables de dimensions",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(Source & \"\\Cas Pratique.xlsx\"), null, true),",
                "    #\"Sous famille_Sheet\" = Source{[Item=\"Sous famille\",Kind=\"Sheet\"]}[Data],",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(#\"Sous famille_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Type modifié1\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"SousFamilleId\", type text}, {\"SousFamille\", type text}, {\"FamilleID\", type text}}),",
                "    #\"Lignes filtrées\" = Table.SelectRows(#\"Type modifié1\", each ([SousFamille] <> \"Essai\")),",
                "    #\"Requêtes fusionnées\" = Table.NestedJoin(#\"Lignes filtrées\", {\"FamilleID\"}, Famille, {\"FamilleId\"}, \"Famille\", JoinKind.LeftOuter),",
                "    #\"Famille développé\" = Table.ExpandTableColumn(#\"Requêtes fusionnées\", \"Famille\", {\"Famille\"}, {\"Famille\"}),",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Famille développé\",{\"FamilleID\"}),",
                "    #\"Lignes filtrées1\" = Table.SelectRows(#\"Colonnes supprimées\", each ([SousFamille] <> null))",
                "in",
                "    #\"Lignes filtrées1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Chronologie",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "N",
              "expression": "Selectedmeasure()"
            },
            {
              "name": "N-1",
              "expression": "calculate(Selectedmeasure(),sameperiodlastyear('Calendrier'[Date Calendrier]))"
            },
            {
              "name": "Var",
              "expression": "Divide((Selectedmeasure()-calculate(Selectedmeasure(),sameperiodlastyear('Calendrier'[Date Calendrier]))),calculate(Selectedmeasure(),sameperiodlastyear('Calendrier'[Date Calendrier])))",
              "formatStringDefinition": {
                "expression": "\"0.00%\""
              }
            }
          ]
        },
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b58c8e04-2aa8-49e8-9d29-8dfea22a1ed1",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "e3beb520-55d3-4f5d-ba7d-9ae72f499ee2",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "isHidden": true,
        "lineageTag": "380e0307-65ff-4763-9e2d-8637bf559de0",
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "CA - Marge",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Nom Indicateur",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a5e1d02-ac43-4d6d-9824-996f26286f14",
            "sourceColumn": "Nom Indicateur",
            "summarizeBy": "none"
          },
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "463f98ec-1836-4270-9b81-06119cd147cb",
            "sourceColumn": "Index",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "4bc69620-b0da-4e92-9da2-2b7fd55a8e70",
        "measures": [
          {
            "name": "Index CA-Marge",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "MAX ( 'CA - Marge'[Index] )",
            "expression": "MAX ( 'CA - Marge'[Index] )",
            "lineageTag": "cbd33900-d475-48d7-89ae-8dd4aa2ab54b"
          },
          {
            "name": "CA-Marge",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": [
              "SWITCH (",
              "    TRUE (),",
              "    [Index CA-Marge] = 1, [CA Total],",
              "    [Index CA-Marge] = 2, [Marge totale]",
              ")"
            ],
            "expression": [
              "SWITCH (",
              "    TRUE (),",
              "    [Index CA-Marge] = 1, [CA Total],",
              "    [Index CA-Marge] = 2, [Marge totale]",
              ")"
            ],
            "lineageTag": "5de55b6a-47b8-40ac-be75-a72a0bb59b12"
          }
        ],
        "partitions": [
          {
            "name": "CA - Marge-04dbaed8-3019-47fd-a68b-30cf6c97564e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wcs7ITEsrSlVIiSk1MDAyT0xLS8wsSlXSUTJUitWJVvJNLEoH8YyUYmMB\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Nom Indicateur\" = _t, Index = _t]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(Source,{{\"Nom Indicateur\", type text}, {\"Index\", Int64.Type}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Colonne 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e5371271-58a3-4cdc-b446-abd010b97abe",
            "sourceColumn": "Colonne 1",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "9fb40efc-33c4-4bf2-b885-ee97a8b466d8",
        "measures": [
          {
            "name": "Vide",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "\"\"",
            "expression": "\"\"",
            "isHidden": true,
            "lineageTag": "707021c4-3a21-469f-b0e9-c7dbb1ded759"
          }
        ],
        "partitions": [
          {
            "name": "KPI-f3750784-068a-4963-8af7-0014255eb6cc",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Colonne 1\" = _t]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(Source,{{\"Colonne 1\", type text}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_4d7274eb-a370-43df-a354-1ee0cc1dda27",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "739a9902-eb97-4761-8e3c-79bc2feb983d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Année",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "6a2e0eac-253f-46f2-89ed-e8c55c9f144c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoMois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "b79d3ab6-a0b2-46d2-9730-a436c9790fdd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1d615f66-ac5d-4c5b-899c-8cd42c7c11eb",
            "sortByColumn": "NoMois",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NoMois] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "d34a0e86-bbc1-4f38-85eb-15437e080247",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [NoTrimestre]",
            "isHidden": true,
            "lineageTag": "0cdc7379-780c-4499-8f2c-e5ea049388b2",
            "sortByColumn": "NoTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Jour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "5ad430e5-6894-4527-8d05-d464c4f8cacc",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Année",
                "column": "Année",
                "lineageTag": "533c7c5f-3d9f-4615-938b-bc0c86901b12",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "9191a4e6-7aff-456e-b876-4bc27c60d970",
                "ordinal": 1
              },
              {
                "name": "Mois",
                "column": "Mois",
                "lineageTag": "df738213-16f2-43cc-8003-6f50b3b37b0d",
                "ordinal": 2
              },
              {
                "name": "Jour",
                "column": "Jour",
                "lineageTag": "a39f88c5-dc10-42e2-9485-57dca4d3af1e",
                "ordinal": 3
              }
            ],
            "lineageTag": "507177db-dcb2-49a6-8002-a07c4b12f1d8"
          }
        ],
        "isHidden": true,
        "lineageTag": "2ae06f49-79e0-45d5-9c46-1b9649d5d778",
        "partitions": [
          {
            "name": "LocalDateTable_4d7274eb-a370-43df-a354-1ee0cc1dda27",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendrier'[date -12 mois])), 1, 1), Date(Year(MAX('Calendrier'[date -12 mois])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Tempo",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "30f8ed7e4ced4625b9353b88a93f82cc"
          }
        ],
        "columns": [
          {
            "name": "datemin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "cddec6ca-36e7-48e6-8567-3ba138e494e5",
            "sourceColumn": "[datemin]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hiérarchie de dates",
                  "table": "LocalDateTable_9f42d532-2871-464a-9fd2-01ce197590de"
                },
                "isDefault": true,
                "relationship": "40cddd28-3f41-4b4c-931a-0573ebaf788d"
              }
            ]
          },
          {
            "name": "datemax",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "38432585-b160-481a-919e-a30211d0d09b",
            "sourceColumn": "[datemax]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hiérarchie de dates",
                  "table": "LocalDateTable_970ea407-f151-4376-b6fb-9d371f24cc83"
                },
                "isDefault": true,
                "relationship": "64401fa8-8efd-4d32-a841-6f22fa1be5dc"
              }
            ]
          }
        ],
        "lineageTag": "9d18c247-390a-4a9f-8fdd-93a0db3ca018",
        "partitions": [
          {
            "name": "Tempo",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "",
                "",
                "var Xmin = min(Factures[DateFacture])",
                "var Xmax = max(Factures[DateFacture])",
                "",
                "return SUMMARIZECOLUMNS(\"datemin\", Xmin, \"datemax\", Xmax)",
                "",
                ""
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_9f42d532-2871-464a-9fd2-01ce197590de",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "241b1b4d-ef58-4b62-a695-383c6f9cfb47",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Année",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "6314e195-a334-4766-96b9-5607a4f30eeb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoMois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "77a15e60-5267-4b5d-b09f-55b8ef315f69",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e7216114-1ddc-428b-a047-03e755a844b6",
            "sortByColumn": "NoMois",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NoMois] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "aa5e8a29-38a8-49ca-ad0a-5c9134031bb7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [NoTrimestre]",
            "isHidden": true,
            "lineageTag": "e69e8eef-9d7a-46ff-88ad-3aac953f277a",
            "sortByColumn": "NoTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Jour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "0b9017e6-7809-43d8-be23-d31a110c1570",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Année",
                "column": "Année",
                "lineageTag": "1ff5cdf5-bd92-4ab9-adf1-606fab7d3e8f",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "1e72d02b-6a8c-4d84-ba74-7e5bd70d636f",
                "ordinal": 1
              },
              {
                "name": "Mois",
                "column": "Mois",
                "lineageTag": "e45b3842-6ec9-438a-8ad1-2f1add584d9c",
                "ordinal": 2
              },
              {
                "name": "Jour",
                "column": "Jour",
                "lineageTag": "8d9427f3-55e0-4e33-87b5-d0c9964dccf1",
                "ordinal": 3
              }
            ],
            "lineageTag": "436d7334-19f3-4e5d-99ce-4326010d585c"
          }
        ],
        "isHidden": true,
        "lineageTag": "b3a9a60f-735f-47f6-bd6d-4ccfc42c6484",
        "partitions": [
          {
            "name": "LocalDateTable_9f42d532-2871-464a-9fd2-01ce197590de",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Tempo'[datemin])), 1, 1), Date(Year(MAX('Tempo'[datemin])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_970ea407-f151-4376-b6fb-9d371f24cc83",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "768779fa-9f65-4687-87c3-015a17c54054",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Année",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d756c7f0-5c36-4bd9-9a6b-5b2d864f243a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoMois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "8beb7e65-4989-4ae4-8fc2-2c39744f1e5d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d9f7a926-c37b-4456-898b-acba1187de65",
            "sortByColumn": "NoMois",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "NoTrimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([NoMois] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "0ea9f226-1bd4-4229-9c26-fa3db2cd11aa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [NoTrimestre]",
            "isHidden": true,
            "lineageTag": "95b48fa2-6351-4c28-95bd-d915e9718564",
            "sortByColumn": "NoTrimestre",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Jour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "66cc58e8-b994-4fa1-9bcb-6d1ab8687d82",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hiérarchie de dates",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Année",
                "column": "Année",
                "lineageTag": "e2cbc7fa-d533-4e77-ba26-1a14b72a9d93",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "ea6bfc35-ecbf-4130-a4b2-7b75b4978ad5",
                "ordinal": 1
              },
              {
                "name": "Mois",
                "column": "Mois",
                "lineageTag": "c0836d9f-ac53-49d0-a4e5-0a65c20e268f",
                "ordinal": 2
              },
              {
                "name": "Jour",
                "column": "Jour",
                "lineageTag": "2611ad30-e54a-4b20-b4b7-859b96dce348",
                "ordinal": 3
              }
            ],
            "lineageTag": "15a72f61-5e2c-42be-bec2-038eb1361e8d"
          }
        ],
        "isHidden": true,
        "lineageTag": "4b808e51-1315-4b1e-aed5-a36a2b0d4c50",
        "partitions": [
          {
            "name": "LocalDateTable_970ea407-f151-4376-b6fb-9d371f24cc83",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Tempo'[datemax])), 1, 1), Date(Year(MAX('Tempo'[datemax])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "ClusterMappingTable 2",
        "annotations": [
          {
            "name": "ClusterMappingTable",
            "value": "true"
          },
          {
            "name": "__PBI_SemanticLinks",
            "value": "[{\"LinkTarget\":{\"TableName\":\"Factures\",\"TableItemName\":\"NumeroFacture (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
          }
        ],
        "columns": [
          {
            "name": "NumeroFacture",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Factures\",\"TableItemName\":\"NumeroFacture (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f3a780a8-0f8f-4f65-9314-2e211c1ded70",
            "sourceColumn": "[NumeroFacture]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ClusterId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"Factures\",\"TableItemName\":\"NumeroFacture (clusters)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5ff64ae8-9bce-4a11-b4ca-cb53f781912b",
            "sourceColumn": "[ClusterId]",
            "summarizeBy": "count",
            "type": "calculatedTableColumn"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "381df35f-158a-433f-9d44-612c58b0076b",
        "partitions": [
          {
            "name": "ClusterMappingTable 2",
            "mode": "import",
            "source": {
              "expression": [
                "VAR __ValueFilterDM0 = ",
                "\tFILTER(",
                "\t\tKEEPFILTERS(",
                "\t\t\tSUMMARIZECOLUMNS(",
                "\t\t\t\t'Factures'[NumeroFacture],",
                "\t\t\t\t\"CA_Total\", 'Indicateurs'[CA Total],",
                "\t\t\t\t\"CA_30_40_\", 'Indicateurs'[CA 30-40%],",
                "\t\t\t\t\"CA_30_40\", 'Indicateurs'[CA 30-40],",
                "\t\t\t\t\"Tx_de_marge\", 'Indicateurs'[Tx de marge]",
                "\t\t\t)",
                "\t\t),",
                "\t\t[Tx_de_marge] < 0.4",
                "\t)",
                "",
                "VAR __DS0Core = ",
                "\tSUMMARIZECOLUMNS(",
                "\t\t'Factures'[NumeroFacture],",
                "\t\t__ValueFilterDM0,",
                "\t\t\"CA_Total\", 'Indicateurs'[CA Total],",
                "\t\t\"CA_30_40_\", 'Indicateurs'[CA 30-40%],",
                "\t\t\"CA_30_40\", 'Indicateurs'[CA 30-40],",
                "\t\t\"Tx_de_marge\", 'Indicateurs'[Tx de marge]",
                "\t)",
                "",
                "VAR __DataTransformT0 = ",
                "\tKMeansClustering(",
                "\t\tSELECTCOLUMNS(",
                "\t\t\t__DS0Core,",
                "\t\t\t\"NumeroFacture\", 'Factures'[NumeroFacture],",
                "\t\t\t\"CA_Total\", [CA_Total],",
                "\t\t\t\"CA_30_40_\", [CA_30_40_],",
                "\t\t\t\"CA_30_40\", [CA_30_40],",
                "\t\t\t\"Tx_de_marge\", [Tx_de_marge]",
                "\t\t),",
                "\t\t{(\"[NumeroFacture]\", \"Item\"),",
                "\t\t\t(\"[CA_Total]\", \"Attribute\"),",
                "\t\t\t(\"[CA_30_40_]\", \"Attribute\"),",
                "\t\t\t(\"[CA_30_40]\", \"Attribute\"),",
                "\t\t\t(\"[Tx_de_marge]\", \"Attribute\")},",
                "\t\t{(\"[NumeroFacture]\", BLANK()),",
                "\t\t\t(\"ClusterId\", \"ClusterId\")},",
                "\t\t4",
                "\t)",
                "",
                "RETURN __DataTransformT0"
              ],
              "retainDataTillForceCalculate": true,
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}